import { Question } from '../types';

export const domain3ExamQuestions: Question[] = [
  {
    id: 3901,
    domain: 3,
    domainName: 'Evaluation & Tuning',
    topic: 'Scenario: RAGAS Metric Selection',
    question: 'Your RAG-based knowledge management agent scores: Faithfulness=0.91, Answer Relevancy=0.88, Context Precision=0.43, Context Recall=0.89. The product team says "answers seem accurate but users complain the agent often misses the most relevant source document." Which single RAGAS metric explains this complaint and what does a score of 0.43 mean?',
    options: {
      A: 'Faithfulness=0.91 explains it — the agent is too faithful to irrelevant documents and not faithful enough to the right ones',
      B: 'Context Precision=0.43 explains it — this means only 43% of the retrieved context chunks are actually relevant to the question. The retriever is pulling many irrelevant chunks, diluting the signal and causing the LLM to miss or deprioritize the most relevant source',
      C: 'Answer Relevancy=0.88 explains it — a score below 1.0 means 12% of answers are off-topic, which users experience as "missing" the right source',
      D: 'Context Recall=0.89 explains it — 11% of relevant chunks are not retrieved, causing the agent to miss some sources',
    },
    answer: 'B',
    explanation: 'Context Precision measures: of the chunks retrieved, what fraction are actually relevant? A score of 0.43 means 57% of retrieved chunks are noise — the retriever is fetching irrelevant content. When the LLM processes 10 chunks and 6 are irrelevant, it often "drowns out" the relevant source, causing users to feel the agent missed the right document. Context Recall (0.89) measures whether the ground-truth relevant chunks were retrieved at all — high recall means the right chunks ARE in the retrieval set, but low precision means they\'re buried in noise. Fix: improve retrieval precision via re-ranking, metadata filtering, or a smaller chunk count.',
    keywords: ['RAGAS', 'context precision', 'context recall', 'faithfulness', 'answer relevancy', 'RAG evaluation'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 3902,
    domain: 3,
    domainName: 'Evaluation & Tuning',
    topic: 'Scenario: LLM-as-Judge Calibration',
    question: 'You are using GPT-4o as a judge to evaluate your agent\'s response quality on a 1-5 scale. You notice the judge consistently gives scores of 4-5 even for responses your human reviewers rate 2-3. Select TWO techniques that address this judge calibration failure.',
    options: {
      A: 'Switch to a larger judge model — GPT-4o is too lenient; a frontier model will be stricter by default',
      B: 'Calibrate the judge with few-shot examples in the judge prompt: include 2-3 examples of poor responses (score 2) with reasoning for why they score low, and 2-3 examples of excellent responses (score 5) with reasoning — anchor the judge\'s scale to human judgments',
      C: 'Use a reference-based evaluation metric instead of reference-free LLM-as-judge — compare against a ground truth answer using exact match or BLEU score',
      D: 'Add explicit evaluation criteria to the judge prompt: "Score 1 if the response hallucinates facts. Score 2 if it misses key information. Score 3 if accurate but incomplete..." — rubric-based prompting constrains the judge to use the full scale',
      E: 'Run each response through 5 different LLM judges and average the scores — ensemble judging reduces individual judge bias',
    },
    answer: 'BD',
    explanation: 'LLM-as-judge positivity bias (leniency) is a known failure mode. Option B (few-shot calibration): providing the judge with examples anchored to your human-rated scale directly teaches it what a "2" looks like versus a "5" — this is the most effective single intervention. Option D (rubric-based prompting): a detailed scoring rubric that maps specific failure modes to specific scores forces the judge to evaluate against criteria rather than overall impressiveness — preventing the "sounds good, scores 4" heuristic. Option A is false — larger models often have stronger positivity bias. Option C (BLEU/exact match) doesn\'t address open-ended quality evaluation. Option E (ensemble) reduces variance but doesn\'t fix systematic positivity bias.',
    keywords: ['LLM-as-judge', 'positivity bias', 'few-shot calibration', 'rubric-based', 'judge calibration'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 3903,
    domain: 3,
    domainName: 'Evaluation & Tuning',
    topic: 'Scenario: SFT vs DPO Selection',
    question: 'Your customer service agent has been fine-tuned with SFT on 50k human-written responses. Evaluation shows it produces accurate responses but they are too verbose (avg 400 words vs. desired 150 words) and occasionally uses inconsistent tone. You have a dataset of 5,000 preference pairs where human raters selected the better of two model responses. Which fine-tuning approach should you use next?',
    options: {
      A: 'Run another round of SFT on a filtered subset of short, consistent responses — SFT can enforce length and style constraints if the training data is curated correctly',
      B: 'Use DPO (Direct Preference Optimization) with your 5,000 preference pairs — DPO directly optimizes the model to prefer the chosen response over the rejected one, effectively learning human preferences for conciseness and consistent tone without a separate reward model',
      C: 'Use RLHF with a reward model trained on the preference pairs, then PPO to fine-tune — this is the gold standard for preference alignment',
      D: 'Add a post-generation truncation step that cuts responses at 150 words — no fine-tuning needed',
    },
    answer: 'B',
    explanation: 'DPO is the correct choice when you have preference pair data and want to align style/quality preferences (conciseness, tone) rather than factual correctness. DPO directly optimizes the log-likelihood ratio between chosen and rejected responses using a simple classification objective — no reward model, no PPO training loop, significantly simpler than RLHF. With 5,000 preference pairs where raters chose the shorter, more consistent response, DPO will shift the model\'s output distribution toward those preferred characteristics. Option A (SFT on filtered data) can work but throws away the paired preference signal. Option C (full RLHF) is more powerful but requires a trained reward model and PPO infrastructure — overkill for this use case. Option D (truncation) produces cut-off responses, not naturally concise ones.',
    keywords: ['DPO', 'SFT', 'RLHF', 'preference pairs', 'fine-tuning', 'preference optimization'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 3904,
    domain: 3,
    domainName: 'Evaluation & Tuning',
    topic: 'Scenario: LoRA Rank Selection',
    question: 'You are fine-tuning a 70B parameter LLM using LoRA for a specialized legal document summarization task. Your GPU budget allows r=8 or r=64. Training data: 12,000 curated legal summaries. Select TWO factors that should drive your rank selection decision.',
    options: {
      A: 'r=8 is always safer — lower rank prevents overfitting regardless of task complexity or data size',
      B: 'Task complexity: legal summarization requires learning domain-specific patterns (citation formats, legal terminology, hedging language) that benefit from higher rank (r=32-64) — a higher rank increases the number of trainable parameters in the adapter, allowing more expressive adaptation',
      C: 'Dataset size: with 12,000 training examples, you have sufficient data to support higher-rank adapters (r=32-64) without overfitting — small datasets (under 1,000 examples) warrant lower ranks to prevent overfitting',
      D: 'GPU memory: higher rank directly increases GPU memory usage during training proportionally, so r=64 requires exactly 8x more GPU memory than r=8',
      E: 'r=64 is always better — more trainable parameters always produce better task adaptation',
    },
    answer: 'BC',
    explanation: 'LoRA rank selection involves two key factors: (B) Task complexity determines how much adaptation capacity is needed. Legal summarization is domain-specific and stylistically complex — it requires the model to learn legal citation patterns, hedging language ("the court held..."), and structured summary formats. This complexity benefits from higher rank (r=32-64). (C) Dataset size determines overfitting risk. 12,000 examples provides sufficient signal to train a higher-rank adapter. With under 1,000 examples, r=4-8 reduces overfitting risk. Option A ("r=8 always safer") ignores task complexity. Option D is incorrect — LoRA memory scales roughly as 2×r×d×layers, not 8× from r=8 to r=64. Option E ("r=64 always better") is false — higher rank without sufficient data overfits.',
    keywords: ['LoRA', 'rank', 'fine-tuning', 'overfitting', 'task complexity', 'dataset size'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 3905,
    domain: 3,
    domainName: 'Evaluation & Tuning',
    topic: 'Scenario: NeMo Curator Pipeline',
    question: 'You are building a fine-tuning dataset for a technical support agent using NVIDIA NeMo Curator. Your raw data is 500GB of support tickets, chat logs, and documentation. Which sequence of NeMo Curator operations correctly prepares this data for SFT?',
    options: {
      A: 'Deduplication → Quality filtering (heuristic classifiers for length, language, technical content) → PII removal → Format conversion to SFT instruction pairs (prompt/response)',
      B: 'Format conversion first → then deduplication → then quality filtering → then PII removal',
      C: 'PII removal → Deduplication → Quality filtering → Format conversion to SFT pairs',
      D: 'Quality filtering only — deduplication and PII removal are handled automatically by the NeMo fine-tuning framework during training',
    },
    answer: 'C',
    explanation: 'The correct NeMo Curator pipeline order: (1) PII removal FIRST — before any data analysis or storage, remove personally identifiable information from support tickets and chat logs to comply with data privacy requirements. (2) Deduplication — remove near-duplicate tickets that would cause the model to overfit to repeated patterns. NeMo Curator\'s fuzzy deduplication (MinHash LSH) handles this at scale. (3) Quality filtering — heuristic and model-based classifiers remove low-quality content (short responses, non-English, irrelevant tickets). (4) Format conversion — convert filtered, clean data to SFT instruction pairs ({"prompt": "...", "response": "..."}). Option A does deduplication before PII removal — a privacy risk. Option D is false — NeMo does not auto-handle PII or deduplication during training.',
    keywords: ['NeMo Curator', 'PII removal', 'deduplication', 'quality filtering', 'SFT dataset', 'pipeline order'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 3906,
    domain: 3,
    domainName: 'Evaluation & Tuning',
    topic: 'Scenario: AgentEval Trajectory Evaluation',
    question: 'Your coding agent produces correct final answers 78% of the time but your QA team reports that the paths the agent takes are often inefficient — calling 8 tools when 3 would suffice. Traditional answer-correctness evaluation misses this. Select TWO evaluation approaches that specifically assess agent trajectory quality.',
    options: {
      A: 'Use RAGAS Faithfulness metric — it measures whether the agent\'s reasoning is faithful to its retrieved context, which correlates with trajectory efficiency',
      B: 'Use AgentEval trajectory evaluation: compare the agent\'s tool call sequence against a reference trajectory for the same task, scoring on step count, tool selection accuracy, and unnecessary detour rate',
      C: 'Evaluate intermediate steps using an LLM-as-judge that scores each tool call: "Was this tool call necessary given what the agent already knew?" — aggregating step-level necessity scores gives a trajectory efficiency metric',
      D: 'Only evaluate final answer correctness — intermediate step quality doesn\'t matter as long as the answer is correct',
      E: 'Count the number of tool calls per task and set a maximum threshold (e.g., 5 tool calls max) — any agent exceeding the threshold fails the trajectory evaluation',
    },
    answer: 'BC',
    explanation: 'Option B (AgentEval trajectory evaluation): AgentEval specifically evaluates agent trajectories by comparing against reference paths. It measures: correct tool selection, minimal step count, absence of unnecessary tool calls, and correct ordering. This directly addresses "8 tools when 3 would suffice." Option C (LLM-as-judge for step necessity): at each step, an LLM judge asks "was this tool call necessary given prior information?" — a principled way to detect redundant steps without needing a reference trajectory. Option A (RAGAS Faithfulness) evaluates RAG output quality, not tool call efficiency. Option D ignores trajectory quality entirely. Option E (hard tool count threshold) is a crude proxy that penalizes complex tasks that legitimately need many tools.',
    keywords: ['AgentEval', 'trajectory evaluation', 'tool call efficiency', 'LLM-as-judge', 'step necessity'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 3907,
    domain: 3,
    domainName: 'Evaluation & Tuning',
    topic: 'Scenario: Benchmark Selection',
    question: 'You are evaluating whether your fine-tuned LLM is ready for deployment as a coding agent. You have three benchmark options: HumanEval, SWE-bench, and your own internal task suite of 200 real bugs from your codebase. Which evaluation strategy is most appropriate for predicting real-world performance?',
    options: {
      A: 'HumanEval only — it is the industry-standard benchmark and a high HumanEval score guarantees strong real-world coding performance',
      B: 'SWE-bench only — it tests real GitHub issues which is more realistic than HumanEval\'s toy problems',
      C: 'Run all three: HumanEval for standardized comparison with published models, SWE-bench for realistic agentic coding evaluation, and your internal suite as the primary production readiness signal — internal benchmarks on your actual tasks are the strongest predictor of deployment performance',
      D: 'Skip benchmarks and deploy to 1% of traffic — real production performance data is more reliable than any benchmark',
    },
    answer: 'C',
    explanation: 'No single benchmark predicts real-world performance alone: HumanEval (function completion) tests narrow coding competency and is heavily contaminated in training data. SWE-bench (real GitHub issues) tests agentic, multi-file problem solving more realistically. Your internal 200-task suite on your actual codebase is the strongest signal — it tests exactly the distribution of bugs and code patterns your agent will face in production. Using all three gives: comparability with published models (HumanEval), realistic agentic evaluation (SWE-bench), and direct production relevance (internal). Option A is incorrect — HumanEval scores don\'t correlate strongly with SWE-bench or real-world agent performance. Option D (shadow deploy) is valid eventually but premature without offline evaluation.',
    keywords: ['HumanEval', 'SWE-bench', 'benchmark', 'internal evaluation suite', 'coding agent', 'evaluation strategy'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 3908,
    domain: 3,
    domainName: 'Evaluation & Tuning',
    topic: 'Scenario: Evaluation Data Contamination',
    question: 'Your fine-tuned model scores 94% on your evaluation set. Before declaring success, your team lead asks you to check for data contamination. Select TWO checks that are most important to run before trusting the 94% score.',
    options: {
      A: 'Verify that evaluation examples were created AFTER the fine-tuning dataset cutoff date — temporally separated data prevents training contamination',
      B: 'Run n-gram overlap analysis between training data and evaluation data — flag any evaluation examples with >40% 8-gram overlap with training examples',
      C: 'Compare model performance on the evaluation set vs. a held-out test set that was never shown to anyone on the team — a 15%+ gap indicates overfitting to the evaluation set',
      D: 'Check if the fine-tuning data was sourced from the same document collection as the evaluation data — if so, the model may have memorized evaluation-specific patterns',
      E: 'Evaluate on a public benchmark like MMLU instead — public benchmarks are guaranteed contamination-free',
    },
    answer: 'BC',
    explanation: 'Option B (n-gram overlap analysis): direct string overlap between train and eval data is the most reliable contamination signal. High 8-gram overlap means the model has likely "memorized" evaluation examples during training, inflating the score. NeMo Curator and other data curation tools provide exact and fuzzy deduplication that can catch this. Option C (held-out test set comparison): if your evaluation set was used to guide model selection or hyperparameter tuning, it\'s contaminated by selection bias. A pristine held-out set that no team member touched reveals true generalization. Option A (temporal separation) is a good practice but contamination can still occur within the same time period. Option D (same document collection) is weaker — same source doesn\'t imply same examples. Option E is false — public benchmarks are frequently contaminated in LLM training data.',
    keywords: ['data contamination', 'n-gram overlap', 'held-out test set', 'evaluation integrity', 'NeMo Curator'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 3909,
    domain: 3,
    domainName: 'Evaluation & Tuning',
    topic: 'Scenario: Faithfulness vs Answer Relevancy Tradeoff',
    question: 'After optimizing your RAG pipeline for Faithfulness (0.95), you notice Answer Relevancy dropped from 0.82 to 0.61. Users report the agent now gives "safe" answers that cite the document but don\'t actually answer what was asked. What is the root cause of this tradeoff and how do you resolve it?',
    options: {
      A: 'This is expected — Faithfulness and Answer Relevancy always trade off. Accept the lower Answer Relevancy as the cost of factual accuracy',
      B: 'You over-optimized for faithfulness by restricting the LLM to only quote retrieved text verbatim. The LLM stopped synthesizing information into direct answers. Fix: allow the LLM to synthesize and paraphrase retrieved content while maintaining attribution, rather than restricting to direct quotation',
      C: 'The retrieval system is returning irrelevant documents, causing the LLM to answer from the wrong context. Fix: improve retrieval precision',
      D: 'Lower the Faithfulness threshold from 0.95 to 0.75 — this will free the LLM to generate more relevant answers at the cost of occasional hallucination',
    },
    answer: 'B',
    explanation: 'This is a classic over-correction failure. Faithfulness measures "is every claim in the answer supported by retrieved context?" When optimized too aggressively (via a "only use retrieved text" instruction), the LLM starts quoting chunks verbatim rather than synthesizing them into direct answers. A direct question "What is the refund policy?" answered with a verbatim paragraph about return procedures has high Faithfulness (every word is in the document) but low Answer Relevancy (doesn\'t directly answer the question). Fix: the LLM should synthesize retrieved content into a direct answer, with attribution ("According to [source], the refund policy is 30 days for X cases..."). This maintains factual grounding without sacrificing directness.',
    keywords: ['faithfulness', 'answer relevancy', 'RAGAS', 'synthesis vs quotation', 'RAG optimization'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 3910,
    domain: 3,
    domainName: 'Evaluation & Tuning',
    topic: 'Scenario: Synthetic Data Generation for Fine-Tuning',
    question: 'You need 50,000 training examples for fine-tuning a specialized chemistry agent but only have 2,000 real expert-annotated Q&A pairs. Select TWO approaches for generating high-quality synthetic training data using NVIDIA\'s toolchain.',
    options: {
      A: 'Use NeMo Curator\'s synthetic data generation pipeline: use a frontier model (GPT-4 or Llama-3.1-70B via NIM) to generate question variants and answers from your 2,000 seeds, then filter with NeMo Curator quality classifiers to keep only high-quality synthetic examples',
      B: 'Fine-tune the target model on the 2,000 real examples first, then use it to generate synthetic data for the second round — the model generates its own training data',
      C: 'Use a teacher-student approach: a large frontier model (the teacher) generates detailed chain-of-thought explanations for chemistry problems, a smaller NeMo model (the student) is fine-tuned on these synthetic CoT examples to learn reasoning patterns the smaller model couldn\'t otherwise learn',
      D: 'Augment by paraphrasing: generate 25 paraphrases of each of the 2,000 real examples using string manipulation (synonym replacement, sentence reordering) to reach 50,000 examples',
      E: 'Skip synthetic data and use the 2,000 real examples with a very high LoRA rank to memorize the training set',
    },
    answer: 'AC',
    explanation: 'Option A (NeMo Curator synthetic pipeline): NeMo Curator supports synthetic data generation workflows — use a capable frontier model via NIM to generate chemistry Q&A variations from your 2,000 seeds (question reformulations, difficulty variations, edge cases), then apply quality filters (classifier-based scoring, deduplication, chemistry accuracy verification) to select the best synthetic examples. Option C (teacher-student knowledge distillation): a frontier model generates chain-of-thought reasoning traces for chemistry problems — the smaller model learns the reasoning pattern, not just the answer. This transfers capabilities the smaller model couldn\'t develop from limited real data alone. Option B (model generates its own data) produces distribution collapse — the model amplifies its own biases. Option D (paraphrasing) produces near-duplicate examples with minimal diversity gain.',
    keywords: ['synthetic data', 'NeMo Curator', 'teacher-student', 'knowledge distillation', 'chain-of-thought', 'fine-tuning'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
];
