import { Question } from '../types';

export const domain4ExamQuestions: Question[] = [
  {
    id: 4901,
    domain: 4,
    domainName: 'Deployment & Scaling',
    topic: 'Scenario: NIM Kubernetes Deployment',
    question: 'You are deploying NVIDIA NIM (Llama-3.1-70B) on Kubernetes. Your team wants auto-scaling based on GPU utilization and request queue depth, and requires that GPU memory is fully released between model swaps. Select TWO Kubernetes configurations that are required for a production NIM deployment.',
    options: {
      A: 'Set `resources.limits.nvidia.com/gpu: 1` in the container spec and use NVIDIA\'s device plugin DaemonSet — NIM requires explicit GPU resource allocation via the NVIDIA Kubernetes device plugin to access GPU hardware',
      B: 'Configure a Horizontal Pod Autoscaler (HPA) with a custom metric for GPU utilization (via DCGM Exporter + Prometheus adapter) — standard CPU/memory HPA metrics don\'t capture GPU saturation',
      C: 'Use NIM\'s built-in Kubernetes operator which automatically handles GPU memory management, pod scheduling, and model caching without manual resource configuration',
      D: 'Set `nvidia.com/mig.strategy: single` in the node configuration to enable Multi-Instance GPU partitioning — required for running multiple NIM replicas on a single GPU',
      E: 'Mount the NGC API key as a Kubernetes Secret and pass it as `NGC_API_KEY` environment variable — NIM requires NGC authentication to pull model weights on first startup',
    },
    answer: 'AE',
    explanation: 'Option A: The NVIDIA Kubernetes device plugin is mandatory — it exposes GPU resources to Kubernetes pods via `nvidia.com/gpu` resource requests/limits. Without it, pods cannot access GPU hardware. NIM containers must declare GPU resource requirements. Option E: NIM pulls model weights from NGC (NVIDIA GPU Cloud) on first startup and requires an NGC API key. Storing it as a Kubernetes Secret and injecting via environment variable is the production-standard approach. Option B (custom HPA) is a best practice but not required for initial deployment. Option C is false — NIM does not have a built-in Kubernetes operator at this time. Option D (MIG) is for multi-tenant GPU partitioning, not required for single-model NIM deployment.',
    keywords: ['NIM', 'Kubernetes', 'NVIDIA device plugin', 'NGC API key', 'GPU resource', 'deployment'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 4902,
    domain: 4,
    domainName: 'Deployment & Scaling',
    topic: 'Scenario: TensorRT-LLM Quantization Tradeoffs',
    question: 'You are optimizing a 70B LLM for inference using TensorRT-LLM. You must choose between FP16, INT8 (weight-only quantization), and INT4 (GPTQ/AWQ). Your SLA requires p99 latency <2s and accuracy within 2% of the FP16 baseline on your domain benchmark. Which quantization level should you choose and why?',
    options: {
      A: 'FP16 — never quantize a production model, the accuracy loss is unacceptable for enterprise use',
      B: 'INT8 weight-only quantization — reduces model size by ~50% vs FP16, reduces memory bandwidth requirements enabling faster inference, and typically shows <1% accuracy degradation on most tasks — meets both the latency SLA and 2% accuracy requirement',
      C: 'INT4 (GPTQ/AWQ) — maximum memory reduction (4x vs FP16), enabling the 70B model to fit on a single A100 80GB vs the two required for FP16, at the cost of 2-5% accuracy degradation depending on the task',
      D: 'Always choose INT4 — NVIDIA\'s AWQ algorithm has eliminated quantization accuracy loss entirely',
    },
    answer: 'B',
    explanation: 'INT8 weight-only quantization is the correct choice given the constraints: (1) <1% accuracy degradation on typical tasks comfortably meets the 2% SLA. (2) ~50% memory reduction vs FP16 reduces GPU memory bandwidth pressure, directly improving inference speed to meet p99 <2s. (3) TensorRT-LLM\'s SmoothQuant and weight-only INT8 are production-proven for 70B models. INT4 (Option C) provides more compression but 2-5% accuracy degradation may violate the 2% accuracy requirement — too risky without prior measurement on your specific domain benchmark. Option A ignores that INT8 is routinely used in production with negligible accuracy impact. Option D is false — INT4 quantization still incurs accuracy loss on complex reasoning tasks.',
    keywords: ['TensorRT-LLM', 'INT8', 'INT4', 'quantization', 'FP16', 'latency SLA', 'accuracy tradeoff'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 4903,
    domain: 4,
    domainName: 'Deployment & Scaling',
    topic: 'Scenario: Triton Dynamic Batching',
    question: 'Your Triton Inference Server is handling variable-rate LLM inference requests. During peak hours (100 req/s), GPU utilization is 40% despite high queue depth. During off-peak (5 req/s), GPU utilization is 8%. Select TWO Triton configurations that would improve GPU utilization and throughput without increasing latency beyond acceptable bounds.',
    options: {
      A: 'Enable dynamic batching in the model config with `max_queue_delay_microseconds: 5000` — Triton will wait up to 5ms to accumulate a batch before processing, trading minimal latency increase for dramatically higher GPU utilization',
      B: 'Set `max_batch_size: 32` in the model configuration — allows Triton to batch up to 32 concurrent requests into a single GPU forward pass, multiplying throughput proportionally',
      C: 'Disable batching entirely and increase the number of model instances — parallelism through replication is always better than batching for LLM inference',
      D: 'Enable continuous batching (in-flight batching) via the TensorRT-LLM backend — allows new requests to join a running decode loop mid-generation, filling GPU compute gaps between token generations',
      E: 'Set GPU utilization target to 100% in the Triton config — Triton will automatically batch to fill GPU capacity',
    },
    answer: 'AD',
    explanation: 'Option A (dynamic batching with queue delay): `max_queue_delay_microseconds` tells Triton to wait up to N microseconds to form a batch. At 5ms delay, peak throughput increases dramatically while adding only 5ms worst-case latency — acceptable for most SLAs. Option D (continuous/in-flight batching via TensorRT-LLM backend): for LLM autoregressive generation, different requests are at different decode steps. Continuous batching interleaves token generation across requests, filling the GPU at each step. This is the most significant throughput improvement for LLM serving — NVIDIA\'s TensorRT-LLM backend supports this natively. Option B (max_batch_size) is a prerequisite, not a configuration that enables batching by itself. Option C is wrong — LLM inference is compute-bound, not just parallelism-bound; batching is essential. Option E doesn\'t exist in Triton.',
    keywords: ['Triton', 'dynamic batching', 'continuous batching', 'in-flight batching', 'GPU utilization', 'TensorRT-LLM'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 4904,
    domain: 4,
    domainName: 'Deployment & Scaling',
    topic: 'Scenario: Canary Deployment for LLMs',
    question: 'You are deploying a new version of your production LLM (fine-tuned on 6 months of new data) that serves 50,000 requests/day. You cannot afford a full rollback if the new model degrades user experience. What is the correct canary deployment strategy?',
    options: {
      A: 'Deploy the new model to production, run for 24 hours, then compare metrics — the 24-hour window provides sufficient data for a deployment decision',
      B: 'Route 5% of production traffic to the new model version (canary), run both versions behind a load balancer, monitor response quality metrics (LLM-as-judge scores), latency (p50/p95/p99), and error rates in parallel — only increase traffic to the new version when all metrics meet your SLA',
      C: 'Deploy the new version to a separate staging environment with synthetic traffic, validate there, then do a full cutover — staging validation eliminates the need for canary in production',
      D: 'Use feature flags to route internal users to the new model first, then expand to all users after a week of internal validation',
    },
    answer: 'B',
    explanation: 'Canary deployment for LLMs: route a small fraction (5-10%) of production traffic to the new model while the old model handles 90-95%. This enables real-world quality comparison with real user queries (not synthetic traffic), minimal blast radius if the new model underperforms, and data-driven rollout decisions. Critical for LLMs specifically: you need real user traffic because LLM quality is query-distribution-dependent — synthetic traffic misses the long tail. Monitor: LLM-as-judge quality scores (or user satisfaction signals), latency (new fine-tuned models can be slower), and error rates. Option A (full deploy, monitor 24h) has no fallback — you\'ve already impacted all users. Option C (staging only) misses production query distribution. Option D (internal users only) is a valid first step but "internal" users ask different questions than customers.',
    keywords: ['canary deployment', 'traffic splitting', 'LLM deployment', 'rollout strategy', 'quality monitoring'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 4905,
    domain: 4,
    domainName: 'Deployment & Scaling',
    topic: 'Scenario: KV Cache Optimization',
    question: 'Your LLM serving infrastructure shows p99 latency of 8.2s for requests with long system prompts (2,000+ tokens) that repeat across most requests. GPU memory utilization is 78%. Select TWO optimizations that specifically address this bottleneck.',
    options: {
      A: 'Enable prefix caching (KV cache prefix reuse) in TensorRT-LLM or vLLM — requests sharing the same system prompt prefix reuse the pre-computed KV cache for those tokens, eliminating redundant prefill computation for shared prefixes',
      B: 'Increase the context length limit from 4k to 8k tokens — longer context windows reduce the proportion of the window occupied by the system prompt',
      C: 'Move the system prompt content into the model weights via fine-tuning — after fine-tuning, the system prompt is no longer needed at inference time, eliminating prefill cost entirely',
      D: 'Use paged attention (as in vLLM\'s PagedAttention or TensorRT-LLM\'s equivalent) — paged KV cache management eliminates memory fragmentation and allows more concurrent requests, reducing queuing-induced latency',
      E: 'Reduce the system prompt length by 50% using prompt compression techniques — shorter prompts reduce prefill time proportionally',
    },
    answer: 'AD',
    explanation: 'Option A (prefix KV cache): when 90% of requests share the same 2,000-token system prompt, prefix caching means that prefix is computed once and reused across all subsequent requests sharing it. This converts O(n_prompt) prefill cost to O(1) for cached prefixes — the single biggest optimization for this pattern. Both TensorRT-LLM and vLLM support radix-tree-based prefix caching. Option D (paged attention / PagedAttention): fragmented KV cache memory limits concurrent requests. Paged attention manages KV cache in fixed-size pages (like OS virtual memory), eliminating fragmentation and allowing more concurrent sequences — reducing queue depth and p99 latency. Option B (longer context) doesn\'t reduce prefill cost. Option C (fine-tune to embed system prompt) is a valid approach but requires retraining. Option E (compress system prompt) helps but is a content optimization, not an infrastructure optimization.',
    keywords: ['KV cache', 'prefix caching', 'paged attention', 'TensorRT-LLM', 'vLLM', 'prefill optimization'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 4906,
    domain: 4,
    domainName: 'Deployment & Scaling',
    topic: 'Scenario: Multi-GPU Tensor Parallelism',
    question: 'You are deploying a 70B parameter LLM that requires 140GB of GPU memory in FP16. You have 4× A100 80GB GPUs (320GB total). Your traffic pattern is bursty — 0-200 concurrent requests. What is the correct parallelism strategy and configuration?',
    options: {
      A: 'Use pipeline parallelism (PP=4): split the model vertically into 4 pipeline stages, one per GPU. Best for batch processing workloads.',
      B: 'Use tensor parallelism (TP=2): split each layer\'s weight matrices across 2 GPUs (140GB / 2 = 70GB per GPU, fits in A100 80GB). Use the remaining 2 GPUs as a second TP=2 replica for redundancy and throughput doubling.',
      C: 'Use data parallelism (DP=4): load the full 70B model on each of the 4 GPUs. This provides 4x throughput.',
      D: 'Use TP=4: split across all 4 GPUs (35GB per GPU), providing maximum memory headroom for KV cache growth under high concurrency — critical for 200 concurrent requests.',
    },
    answer: 'D',
    explanation: 'With bursty traffic up to 200 concurrent requests, KV cache memory is the critical constraint. At 200 concurrent sequences with long contexts, KV cache can consume 30-60GB+ depending on sequence length. TP=2 (Option B) leaves 80-140=10GB headroom per GPU after the model — insufficient for 200 concurrent requests\' KV cache. TP=4 splits the 140GB model across 4 GPUs (35GB each), leaving 45GB per GPU for KV cache — 180GB total KV cache capacity across the tensor-parallel group. This accommodates the peak burst. Option C (data parallelism) requires 140GB per GPU — impossible on 80GB A100s. Option A (pipeline parallelism) introduces bubble overhead and is suboptimal for real-time inference. TensorRT-LLM\'s tensor parallelism support is production-ready for this configuration.',
    keywords: ['tensor parallelism', 'pipeline parallelism', 'data parallelism', 'multi-GPU', 'KV cache', 'A100'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 4907,
    domain: 4,
    domainName: 'Deployment & Scaling',
    topic: 'Scenario: NGC Model Registry',
    question: 'Your team is deploying a NIM to 3 different environments (dev, staging, prod) with different model versions. Select TWO NGC catalog practices that correctly manage model versioning and deployment consistency across environments.',
    options: {
      A: 'Use NGC container tags with explicit version pinning (`nvcr.io/nim/meta/llama-3.1-70b-instruct:1.2.0`) rather than `:latest` — ensures dev, staging, and prod pull identical model artifacts and prevents unexpected version drift',
      B: 'Pull the model weights at container startup from NGC in each environment — this ensures always-latest weights without manual updates',
      C: 'Store NIM model cache (downloaded weights) in a shared NFS mount accessible to all environments — weights are pulled once from NGC and shared, reducing NGC bandwidth and startup time across all 3 environments',
      D: 'Use NGC org/team namespacing to create separate model registries per environment (dev-models, staging-models, prod-models) — different registries enforce environment isolation at the artifact level',
      E: 'Configure NGC API key rotation to use environment-specific keys with read-only permissions for staging and prod — least-privilege access prevents accidental model overwrite in production',
    },
    answer: 'AC',
    explanation: 'Option A (explicit version pinning): using `:latest` in production is an anti-pattern — a NGC upstream update can silently change behavior across environments. Pinning to a specific version tag ensures dev/staging/prod run identical model artifacts. This is fundamental to reproducible ML deployments. Option C (shared NFS model cache): NIM downloads model weights from NGC on first startup (tens of GB). In multi-environment setups, sharing the weights via NFS means a single NGC pull — reducing startup time from minutes to seconds for environments with cached weights, and reducing NGC egress. Option B (pull at every startup) is wasteful and creates inconsistency. Option D (separate registries) is not a standard NGC pattern for environment management. Option E (key rotation) is a security practice but doesn\'t address versioning consistency.',
    keywords: ['NGC', 'version pinning', 'model cache', 'NIM deployment', 'NFS', 'container tags'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 4908,
    domain: 4,
    domainName: 'Deployment & Scaling',
    topic: 'Scenario: Horizontal Scaling Decision',
    question: 'Your NIM deployment serving a 13B model is experiencing p99 latency of 4.2s at 80 req/s. A single A100 GPU can serve 120 req/s at <2s p99. You have 4 A100 GPUs available. Should you scale horizontally or vertically, and how?',
    options: {
      A: 'Scale vertically: move to an H100 SXM5 80GB which has 2x the memory bandwidth of A100 — hardware upgrade solves the latency problem without architectural changes',
      B: 'Scale horizontally: deploy 2-3 NIM replicas behind a load balancer, each running the 13B model on its own A100. The 13B model fits comfortably in 80GB (requires ~26GB in FP16), so each replica handles full requests independently. This linearly increases throughput and reduces per-replica queue depth, improving latency.',
      C: 'Scale with tensor parallelism across 4 GPUs (TP=4): split the 13B model across all 4 A100s, giving 4x memory headroom for KV cache growth',
      D: 'Increase the Triton max_queue_delay to 50ms to form larger batches — batch efficiency improvements eliminate the need for additional replicas',
    },
    answer: 'B',
    explanation: 'For a 13B model (~26GB FP16), a single A100 80GB has abundant memory (54GB headroom for KV cache). The bottleneck is throughput (compute), not memory. The correct solution is horizontal scaling: deploy multiple independent NIM replicas, each serving the full model on its own A100. A load balancer distributes requests across replicas. With 2 replicas, effective throughput doubles from 120 to 240 req/s, and per-replica queue depth halves — reducing p99 latency. Option A (H100 upgrade) is expensive and doesn\'t provide the 4x headroom available from horizontal scaling with existing A100s. Option C (TP=4 for 13B) is wasteful — TP is needed when a model doesn\'t fit on one GPU, which is not the case here. Option D (larger batches) increases throughput but also increases latency per request.',
    keywords: ['horizontal scaling', 'NIM replicas', 'load balancer', 'tensor parallelism', 'throughput', 'A100'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 4909,
    domain: 4,
    domainName: 'Deployment & Scaling',
    topic: 'Scenario: A/B Testing LLM Versions',
    question: 'You have deployed a fine-tuned LLM (Model B) alongside the base model (Model A) and want to run a statistically rigorous A/B test to determine which produces better user outcomes. Select TWO requirements for a valid A/B test for LLM quality.',
    options: {
      A: 'Assign users randomly and consistently to model variants (sticky sessions) — a user who sees Model A on turn 1 must see Model A throughout their session to avoid confounding from mid-session model switches',
      B: 'Run the test for at least 2 weeks with equal traffic to both variants, and use a pre-specified primary metric (e.g., task completion rate) to determine the winner — avoid analyzing results daily and stopping early when one variant appears to win',
      C: 'Use LLM-as-judge to evaluate responses from both models against the same queries in an offline setting — online A/B testing introduces too many confounding variables (user behavior, time-of-day effects)',
      D: 'Route all power users to Model B — they provide the highest-value feedback for determining production readiness',
      E: 'Calculate required sample size before starting (based on expected effect size, alpha=0.05, power=0.80) to ensure you have enough traffic to detect the minimum meaningful difference before committing to a runtime',
    },
    answer: 'AE',
    explanation: 'Option A (sticky sessions): in conversational AI A/B tests, mid-session model switches are confounding — response quality in turn 5 depends on turns 1-4. Consistent assignment ensures each user\'s full session experience is measured for one model variant. Option E (pre-specified sample size): without pre-computing required N, teams stop when they see early positive results — this is p-hacking (peeking problem). Calculate: minimum detectable effect (e.g., 3% improvement in task completion), alpha=0.05, power=0.80 → required sample size. Start the test, don\'t peek, stop at N. Option B is correct advice but not one of the two most critical requirements — running 2 weeks without pre-specified N can still underpowered. Option C (offline only) misses real user behavior effects. Option D (power user routing) introduces selection bias.',
    keywords: ['A/B testing', 'sticky sessions', 'sample size', 'statistical power', 'peeking problem', 'LLM evaluation'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 4910,
    domain: 4,
    domainName: 'Deployment & Scaling',
    topic: 'Scenario: Cold Start Optimization',
    question: 'Your NIM deployment on Kubernetes has 0 replicas at night (scale-to-zero for cost savings). Morning traffic spikes hit a cold pod that takes 4.5 minutes to start (NGC model weight download + GPU warmup). Users experience 4.5-minute first-request latency. Select TWO strategies that eliminate this cold start penalty.',
    options: {
      A: 'Pre-cache model weights in a PersistentVolumeClaim (PVC) mounted to the NIM pod — on cold start, weights load from local NVMe storage (seconds) instead of downloading from NGC (minutes)',
      B: 'Set `minReplicas: 1` in the HPA config — maintaining one warm replica at all times eliminates cold starts at the cost of ~$50-100/month in idle GPU compute',
      C: 'Use predictive scaling: configure the HPA to scale up 10 minutes before expected traffic spikes (using historical patterns or a scheduled CronJob) — the new pod is warm and serving before the spike arrives',
      D: 'Increase the pod startup timeout in Kubernetes — giving pods more time to start doesn\'t reduce cold start latency',
      E: 'Use a lightweight proxy model (1B parameter) during cold start that serves requests with degraded quality while the 70B NIM warms up — users get fast responses immediately',
    },
    answer: 'AC',
    explanation: 'Option A (PVC weight cache): the dominant cold start cost is model weight download from NGC (70B model = ~140GB download). Mounting a pre-populated PVC with the weights reduces startup from 4.5 minutes (network download) to ~30 seconds (local disk load). This is the most impactful single optimization. Option C (predictive scaling with CronJob): if traffic spikes are predictable (e.g., 9am every weekday), a Kubernetes CronJob can scale the deployment to 1+ replicas at 8:50am — the pod warms up before traffic arrives. No user ever experiences a cold start. Option B (minReplicas=1) eliminates cold starts but wastes an idle A100 GPU all night — Option A+C solve the problem without idle waste. Option D (longer timeout) doesn\'t reduce latency, just allows more time. Option E (proxy model) is a UX mitigation, not a cold start solution.',
    keywords: ['cold start', 'PVC model cache', 'predictive scaling', 'CronJob', 'NIM', 'Kubernetes', 'NGC download'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
];
