import { Question } from '../types';

export const domain6dQuestions: Question[] = [
  { id: 6061, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Active Learning for RAG', difficulty: 'hard', keywords: ['active learning', 'uncertainty sampling', 'knowledge gaps', 'annotation'],
    question: 'Active learning for RAG knowledge base expansion identifies:',
    options: { A: 'Active users who should be given more access to the knowledge base', B: 'Queries where the agent expressed uncertainty or gave low-confidence answers — flagging those topics for priority knowledge acquisition', C: 'The most active (frequently accessed) documents for caching', D: 'Active employees who should contribute to the knowledge base' },
    answer: 'B', explanation: 'Active learning for RAG: track queries where agent says "I don\'t have reliable information" or users rate answers low → these represent knowledge gaps → prioritize acquiring, creating, or curating content for these topics → focus knowledge investment where most needed.' },

  { id: 6062, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Multimodal RAG', difficulty: 'hard', keywords: ['multimodal RAG', 'image retrieval', 'table extraction', 'figure'],
    question: 'Multimodal RAG retrieves information from:',
    options: { A: 'Multiple database modes (read/write)', B: 'Mixed content including text, tables, images, and figures — using appropriate encoders for each modality before retrieval', C: 'Multiple languages simultaneously', D: 'Multiple API endpoints for redundancy' },
    answer: 'B', explanation: 'Multimodal RAG: index text with text embeddings, table data with table encoders, images with CLIP/vision encoders → unified retrieval across modalities → multimodal context injected into LLM. Essential for scientific literature, business reports, and technical documents.' },

  { id: 6063, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Corpus Analysis', difficulty: 'medium', keywords: ['corpus analysis', 'topic modeling', 'coverage', 'gaps'],
    question: 'Topic modeling (LDA, BERTopic) applied to a RAG corpus before deployment:',
    options: { A: 'Improves LLM topic awareness', B: 'Reveals topic distribution, identifies coverage gaps, and enables domain-appropriate chunking strategies tailored to the corpus structure', C: 'Automatically creates topic-based document categories', D: 'Topic modeling must be run continuously, not just at deployment' },
    answer: 'B', explanation: 'Pre-deployment corpus analysis: topic modeling reveals corpus coverage (well-covered vs thin topics), enables per-topic optimization (different chunking for different content types), and identifies gaps requiring additional content before launch.' },

  { id: 6064, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Chunk Metadata', difficulty: 'medium', keywords: ['metadata', 'filtering', 'attributes', 'search enhancement'],
    question: 'Rich metadata attached to knowledge chunks enables:',
    options: { A: 'Reducing storage costs through metadata compression', B: 'Hybrid search combining vector similarity with structured filters (date range, author, document type, department) for precise retrieval', C: 'Metadata only helps with exact keyword search', D: 'Metadata should be minimized to speed up retrieval' },
    answer: 'B', explanation: 'Chunk metadata: {source: "policy_manual_v3", date: "2024-01", department: "HR", doc_type: "policy", page: 47}. Query: "find HR policies from 2024" → vector search for semantics + metadata filter for department=HR AND date≥2024. Precision without recall loss.' },

  { id: 6065, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Contextual Retrieval', difficulty: 'hard', keywords: ['contextual retrieval', 'Anthropic', 'prefix', 'situate'],
    question: 'Anthropic\'s Contextual Retrieval improves chunk embeddings by:',
    options: { A: 'Adding the full document to each chunk before embedding', B: 'Pre-pending a chunk-specific context (generated by LLM summarizing how the chunk fits in the document) before embedding — reducing retrieval failure from decontextualized chunks', C: 'Contextual retrieval uses BM25 context instead of vector search', D: 'Adding user context to all chunks' },
    answer: 'B', explanation: 'Contextual Retrieval: LLM generates "This chunk discusses X in the context of document Y which covers Z" → prepend to chunk → embed enhanced chunk. Addresses the problem: isolated chunks often lack context that makes them retrievable when needed.' },

  { id: 6066, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Dataset Versioning', difficulty: 'medium', keywords: ['DVC', 'dataset versioning', 'reproducibility', 'lineage'],
    question: 'DVC (Data Version Control) for AI knowledge bases provides:',
    options: { A: 'DVD-quality media storage for training videos', B: 'Git-like versioning for large datasets and models — tracking which data went into which model, enabling reproducibility and rollback', C: 'Deduplication and version control for only code files', D: 'DVC is only for structured tabular data' },
    answer: 'B', explanation: 'DVC: stores data in cloud (S3, GCS) but tracks it in git with content hashes. `git checkout v1.2` + `dvc pull` → restore exact dataset state. Critical for reproducibility: "which exact training data produced this model?" and "what changed between versions?"' },

  { id: 6067, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Summary Indexing', difficulty: 'medium', keywords: ['summary index', 'parent-child', 'chunk', 'document summary'],
    question: 'Parent-child chunking strategy (LlamaIndex) improves retrieval by:',
    options: { A: 'Using parent documents to authenticate child chunks', B: 'Indexing small child chunks for precise retrieval while linking to larger parent chunks for context — retrieve with precision, read with context', C: 'Creating hierarchical organization of documents', D: 'Parent-child refers to document creation relationships, not retrieval' },
    answer: 'B', explanation: 'Parent-child: embed small chunks (128 tokens) for precise semantic matching → when retrieved, return surrounding parent chunk (512 tokens) or full document for LLM context. "Find small" but "read large" — precision in retrieval, context in generation.' },

  { id: 6068, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Event-Driven Indexing', difficulty: 'hard', keywords: ['event', 'trigger', 'indexing', 'webhook'],
    question: 'Webhook-triggered indexing in RAG pipelines ensures:',
    options: { A: 'Index updates occur at fixed intervals regardless of changes', B: 'Knowledge base updates within seconds/minutes of source document changes — triggered by the source system when content changes', C: 'Webhooks provide security for knowledge access', D: 'Webhook indexing requires custom connectors for every source' },
    answer: 'B', explanation: 'Event-driven indexing: Confluence page updated → Confluence fires webhook → indexing service receives event → processes and re-embeds changed page → knowledge base updated within ~30 seconds. vs scheduled: knowledge could be hours stale between runs.' },

  { id: 6069, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Long Document Handling', difficulty: 'medium', keywords: ['long document', 'recursive chunking', 'hierarchy', 'splitting'],
    question: 'Recursive character text splitting for long documents first splits on:',
    options: { A: 'Character count only', B: 'Larger separators first (paragraphs → sentences → words → characters), preserving semantic units before resorting to character-level splitting', C: 'Sentence boundaries only', D: 'Recursive splitting starts at character level and works up' },
    answer: 'B', explanation: 'Recursive splitting: try split on "\\n\\n" (paragraphs) first. If chunks too large → split on "\\n" (lines) → if still too large → sentences → words → characters. Preserves natural text boundaries as long as possible, only splitting mid-sentence as last resort.' },

  { id: 6070, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Real-time Tool Data', difficulty: 'medium', keywords: ['real-time', 'tool', 'API', 'live data'],
    question: 'For knowledge that changes frequently (stock prices, weather, live inventory), agents should use:',
    options: { A: 'Daily batch indexing into the knowledge base', B: 'Real-time tool calls to authoritative APIs rather than RAG — ensuring data freshness without knowledge base staleness', C: 'LLM training on the latest data available', D: 'Approximate cached data with acknowledged staleness' },
    answer: 'B', explanation: 'Live data via tools not RAG: current stock prices change every millisecond — don\'t try to index this. Instead: define a stock_price(ticker) tool → agent calls at query time → returns real-time authoritative data. RAG for stable knowledge; tools for live data.' },

  { id: 6071, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Knowledge Pipeline Testing', difficulty: 'medium', keywords: ['pipeline testing', 'golden set', 'regression', 'quality'],
    question: 'Golden dataset testing for RAG pipelines validates:',
    options: { A: 'That all gold-colored documents are properly indexed', B: 'End-to-end retrieval quality on a curated set of (query, expected_chunk) pairs — catching regressions when chunking strategy, embedding model, or index changes', C: 'Only the embedding model quality', D: 'Golden datasets require 10,000+ examples to be useful' },
    answer: 'B', explanation: 'Golden test sets: 100-500 manually verified (query, expected_source_documents) pairs. Run after any pipeline change: do queries retrieve expected chunks? Recall and precision computed → alert if drop > 5%. Catch regressions in chunking, embedding, or index configuration.' },

  { id: 6072, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Negative Knowledge', difficulty: 'hard', keywords: ['negative knowledge', 'absence', 'unknown', 'closed world'],
    question: 'Open World vs Closed World assumptions in AI knowledge systems:',
    options: { A: 'Open world = accessible from anywhere, closed world = private network only', B: 'Closed World: what\'s not in the KB is assumed false; Open World: absence of information doesn\'t mean it\'s false — critical for how agents handle unknown facts', C: 'Open world means unlimited knowledge; closed world means restricted', D: 'World assumptions only matter for formal logic systems, not LLM agents' },
    answer: 'B', explanation: 'Closed World (relational DB): if customer record doesn\'t exist, customer doesn\'t exist. Open World (knowledge graphs, LLMs): absence doesn\'t imply negation — the fact might just not be in the KB. Agents should use OWA: "I don\'t have information about X" ≠ "X is false."' },

  { id: 6073, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Data Source Credibility', difficulty: 'medium', keywords: ['source credibility', 'trust', 'ranking', 'authority'],
    question: 'Assigning credibility weights to knowledge sources in RAG enables:',
    options: { A: 'Legal verification of source authenticity', B: 'Preferring high-credibility sources (official documentation, peer-reviewed) over low-credibility ones (user forums) when conflicts arise', C: 'Source credibility is irrelevant when semantic similarity is high', D: 'All knowledge sources should be treated equally to avoid bias' },
    answer: 'B', explanation: 'Source credibility weighting: medical information from WHO.int (high credibility) > random health blog (low credibility). In retrieval: boost high-credibility sources → agent preferentially uses authoritative sources. Reduces misinformation from low-quality sources in the knowledge base.' },

  { id: 6074, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Adaptive Retrieval', difficulty: 'hard', keywords: ['adaptive', 'dynamic', 'query analysis', 'strategy selection'],
    question: 'Adaptive retrieval strategies select different retrieval approaches based on:',
    options: { A: 'Time of day and server load', B: 'Query type analysis — keyword queries use BM25, conceptual queries use dense retrieval, time-sensitive queries include freshness filters', C: 'Always using the most expensive retrieval method', D: 'User authentication level determines retrieval strategy' },
    answer: 'B', explanation: 'Adaptive retrieval: classify query type → "find documents mentioning SOC 2" (keyword-heavy → BM25 + dense) vs "explain the concepts behind our compliance framework" (conceptual → dense only) vs "latest policy changes" (temporal → filter by recency). Right tool for each query type.' },

  { id: 6075, domain: 6, domainName: 'Knowledge Integration & Data', topic: 'Knowledge Extraction from Conversations', difficulty: 'medium', keywords: ['conversation', 'extraction', 'knowledge', 'learning'],
    question: 'Extracting knowledge from agent-user conversations for knowledge base improvement:',
    options: { A: 'Store all conversations verbatim in the knowledge base', B: 'Identify high-quality Q&A pairs and novel facts from conversations, validate with experts, and selectively add to knowledge base to improve future retrieval', C: 'Conversation data should never be used to improve knowledge bases', D: 'Only store conversations where the user expressed satisfaction' },
    answer: 'B', explanation: 'Conversation-derived knowledge: agent gives an answer that works → extract (question, answer) pair → human review → add to knowledge base (as example Q&A). Continuously improves from actual usage patterns. Must have user consent and privacy compliance.' },
];
