import { Question } from '../types';

export const domain2ExamQuestions: Question[] = [
  {
    id: 2901,
    domain: 2,
    domainName: 'Agent Development',
    topic: 'Scenario: LangGraph vs LangChain Selection',
    question: 'Your team is building a customer onboarding agent that: (1) collects info across multiple turns, (2) conditionally skips steps based on prior answers, (3) may need to loop back to re-ask if validation fails, and (4) must persist state between sessions. A junior engineer proposes using a simple LangChain sequential chain. What is the correct architectural decision and why?',
    options: {
      A: 'LangChain sequential chain is correct — add memory to handle persistence and use if/else in Python to handle conditional logic outside the chain',
      B: 'Use LangGraph: it natively models the workflow as a stateful graph with conditional edges for branching, cycle support for looping back on validation failure, and persistent checkpointing for cross-session state — all of which a sequential chain cannot express',
      C: 'Use CrewAI with a multi-agent crew — assign one agent per onboarding step and let CrewAI handle routing between them',
      D: 'Use a prompt template chain with a "state" field in the prompt that encodes all collected information as a JSON blob, updated on each turn',
    },
    answer: 'B',
    explanation: 'LangGraph is purpose-built for stateful, cyclical workflows: conditional_edges handle branching (skip step 3 if answer X), cycles are first-class (loop back to step 2 if validation fails), and the checkpointer (SqliteSaver, RedisSaver) persists state between sessions natively. LangChain sequential chains are acyclic — they have no loop-back mechanism without external code. Option A (external Python if/else) defeats the purpose of a framework. Option C (CrewAI) adds agent overhead for what is fundamentally a workflow problem. Option D (JSON blob in prompt) is fragile, consumes tokens, and breaks on long sessions.',
    keywords: ['LangGraph', 'LangChain', 'stateful', 'conditional edge', 'checkpointer', 'cyclical'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 2902,
    domain: 2,
    domainName: 'Agent Development',
    topic: 'Scenario: NeMo Agent Toolkit Integration',
    question: 'Your team already has a working LangChain-based research agent. You want to add production-grade observability — token usage per step, tool call latency, and end-to-end trace export to your existing Langfuse instance — without rewriting the agent. Select TWO steps that correctly integrate NVIDIA AgentIQ with your existing LangChain agent.',
    options: {
      A: 'Wrap your LangChain agent\'s invoke call with AgentIQ\'s @aiq.instrument decorator — this instruments all LangChain callbacks automatically',
      B: 'Replace your LangChain LLM with an AgentIQ-native LLM class that has tracing built in, requiring you to rewrite all chain definitions',
      C: 'Configure an AgentIQ workflow config (YAML) that declares your LangChain agent as an external_agent component, enabling AgentIQ to wrap it with instrumentation without code changes inside the agent',
      D: 'Set LANGCHAIN_TRACING_V2=true in environment variables — this connects LangChain\'s built-in tracing to AgentIQ automatically',
      E: 'Point AgentIQ\'s output exporter to your Langfuse endpoint via the telemetry config — AgentIQ supports Langfuse as a first-class OpenTelemetry exporter',
    },
    answer: 'CE',
    explanation: 'AgentIQ is designed for zero-code-change instrumentation of existing agents: (C) The YAML workflow config wraps your existing LangChain agent as an external component — AgentIQ instruments it at the boundary without touching internal agent code. (E) AgentIQ\'s telemetry config supports exporting to Langfuse (and Phoenix, Weave) as first-class OpenTelemetry backends — point the exporter to your Langfuse instance. Option A (decorator) is an AgentIQ pattern but requires code modification inside the agent. Option B (replace LLM class) requires a rewrite, contradicting the requirement. Option D is LangSmith\'s tracing, not AgentIQ.',
    keywords: ['AgentIQ', 'LangChain', 'instrumentation', 'Langfuse', 'OpenTelemetry', 'YAML config'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 2903,
    domain: 2,
    domainName: 'Agent Development',
    topic: 'Scenario: Tool Error Handling',
    question: 'Your agent calls a CRM API tool that intermittently returns HTTP 429 (rate limit) and HTTP 503 (service unavailable) errors. Currently the agent crashes on both errors. What is the correct tool error handling strategy that allows the agent to self-recover?',
    options: {
      A: 'Catch all exceptions in the tool wrapper and return an empty string — the agent will proceed with partial information',
      B: 'For 429: implement exponential backoff with jitter and retry up to 3 times before returning a structured error. For 503: return a structured ToolError object with error_type, error_code, and a human-readable message so the LLM can decide to retry later, use cached data, or inform the user gracefully',
      C: 'Raise the exceptions directly to the agent — LLMs can read Python stack traces and self-correct based on the error message',
      D: 'Wrap the tool in a try/except and restart the entire agent session on any API error',
    },
    answer: 'B',
    explanation: 'Correct tool error handling requires error-type awareness: 429 (rate limit) is transient and retryable — exponential backoff with jitter prevents thundering herd. 503 (service unavailable) may not be immediately retryable — return a structured ToolError so the LLM receives actionable information ("CRM unavailable, retry in ~60s") rather than a Python exception. The LLM can then choose to: skip the CRM step, use cached data, or surface a user-facing message. Option A (empty string) hides errors and produces incorrect output. Option C (raw stack traces) wastes tokens and LLMs don\'t reliably self-correct from exception tracebacks. Option D (full session restart) loses all progress.',
    keywords: ['tool error handling', 'exponential backoff', 'ToolError', 'rate limit', 'structured error'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 2904,
    domain: 2,
    domainName: 'Agent Development',
    topic: 'Scenario: Structured Output Enforcement',
    question: 'Your agent must extract structured data from unstructured medical notes: patient name, diagnosis codes (list), medications (list with dosages), and follow-up date. The current free-text LLM output is inconsistent — sometimes missing fields, sometimes wrong types. Select TWO techniques that enforce structural correctness at the framework level.',
    options: {
      A: 'Use a Pydantic model as the response_format in LangChain\'s structured output chain — the LLM is constrained to produce JSON matching the schema, and Pydantic validates/coerces the output automatically',
      B: 'Add a post-processing regex to extract fields from free-text output — more reliable than schema constraints for medical text',
      C: 'Use OpenAI function calling / tool calling with a JSON schema definition — the LLM\'s output is constrained to the schema at the token sampling level, preventing structurally invalid responses',
      D: 'Increase the LLM temperature to 0.0 — deterministic output is inherently more structured',
      E: 'Add a validation agent that reads the LLM output and flags missing fields, then re-prompts the extraction agent for only the missing fields',
    },
    answer: 'AC',
    explanation: 'Option A (Pydantic + structured output chain): LangChain\'s `.with_structured_output(PydanticModel)` constrains the LLM to produce JSON matching the schema and auto-validates. Option C (function/tool calling with JSON schema): at the model inference level, token sampling is constrained to follow the JSON schema — structurally invalid outputs (wrong types, missing required fields) are impossible by construction. Together, A and C are the two framework-level enforcement mechanisms. Option B (regex) is brittle on variable medical text. Option D (temperature=0) reduces randomness but doesn\'t enforce structure. Option E (validation agent) adds latency and two LLM calls but is complementary, not a replacement for structural enforcement.',
    keywords: ['Pydantic', 'structured output', 'JSON schema', 'function calling', 'LangChain', 'schema validation'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 2905,
    domain: 2,
    domainName: 'Agent Development',
    topic: 'Scenario: CrewAI Role Assignment',
    question: 'You are building a CrewAI pipeline for investment research. You have: a data_fetcher agent (pulls financial data), an analyst_agent (interprets trends), and a report_writer agent (produces the final report). The analyst_agent keeps including raw data tables in its output instead of interpretations. What is the correct CrewAI fix?',
    options: {
      A: 'Add a post-processing step that strips data tables from the analyst_agent\'s output before passing to the report_writer',
      B: 'Refine the analyst_agent\'s role definition and goal in CrewAI to explicitly state "Interpret trends and provide analytical insights — do not reproduce raw data tables. The data_fetcher provides data; your job is analysis only." and update the expected_output field to describe what analysis looks like',
      C: 'Give the analyst_agent a lower temperature so it stays closer to the data rather than interpreting it',
      D: 'Merge the data_fetcher and analyst_agent into a single agent to reduce handoff confusion',
    },
    answer: 'B',
    explanation: 'In CrewAI, agent behavior is driven by the `role`, `goal`, `backstory`, and `expected_output` fields. The analyst_agent is reproducing data because its role doesn\'t explicitly exclude it. The fix is role clarification: "Your role is analyst, not data reporter. Interpret trends, identify anomalies, and provide investment-relevant insights — the data_fetcher handles raw data retrieval." The `expected_output` field should describe the format of analysis (bullet insights, trend narrative) not data tables. Option A (post-processing strip) is a workaround that may remove valid quoted data. Option C (temperature) doesn\'t affect role behavior. Option D (merge agents) violates single-responsibility and degrades specialization.',
    keywords: ['CrewAI', 'role definition', 'goal', 'expected_output', 'agent specialization'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 2906,
    domain: 2,
    domainName: 'Agent Development',
    topic: 'Scenario: Agent Testing Strategy',
    question: 'Your team has a complex multi-agent pipeline (orchestrator → 3 specialists → synthesizer). QA says "we can\'t test the whole pipeline in CI — it\'s too slow and expensive." Select TWO testing strategies that give high confidence without running the full pipeline on every commit.',
    options: {
      A: 'Unit test each agent in isolation using mocked tool responses and mocked LLM outputs (golden outputs for known inputs) — fast, deterministic, runs in CI on every commit',
      B: 'Skip testing entirely and rely on production monitoring to catch regressions — agent behavior is too non-deterministic to test meaningfully',
      C: 'Record real LLM + tool call traces using a trace capture tool, then replay them in tests as mocked responses — tests validate routing logic and state transitions without live API calls',
      D: 'Run the full pipeline with live LLMs and real tools in a nightly CI job — accept the cost for full fidelity',
      E: 'Use property-based testing: define invariants the agent must always satisfy (e.g., "the synthesizer output always cites at least one source") and run 20 randomized inputs against these invariants in CI',
    },
    answer: 'AC',
    explanation: 'Option A (unit tests with mocked LLMs/tools): the fastest, cheapest CI strategy. Mock the LLM to return golden outputs for specific inputs, mock tool responses. Tests validate agent logic, prompt formatting, and state handling — not LLM quality (that\'s for evals). Option C (trace replay): record a real pipeline execution once, save the trace (tool call sequences, LLM I/O), replay in tests. This validates routing logic and state transitions with real-world data shapes but zero API cost. Together A+C provide fast unit-level confidence and realistic integration-level confidence without live API calls. Option B is negligent. Option D is expensive but valid as a nightly job, not a commit-level strategy. Option E is good for invariant testing but requires running the LLM.',
    keywords: ['agent testing', 'mocked LLM', 'trace replay', 'unit testing', 'CI/CD', 'golden outputs'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 2907,
    domain: 2,
    domainName: 'Agent Development',
    topic: 'Scenario: Semantic Kernel Plugin Design',
    question: 'Your team is building agents using Semantic Kernel. You have 3 capability groups: document_processing (5 functions), calendar_management (4 functions), and email_operations (6 functions). A new engineer adds all 15 functions to a single plugin. What is the architectural problem and correct fix?',
    options: {
      A: 'No problem — Semantic Kernel plugins have no function limit and grouping doesn\'t affect performance',
      B: 'A single plugin with 15 functions violates the single-responsibility principle for plugins. Split into 3 plugins (DocumentPlugin, CalendarPlugin, EmailPlugin) — each plugin is a logical grouping of related functions with its own description that helps the planner select the right plugin for a task',
      C: 'The problem is the number of functions — reduce to maximum 5 functions total across all plugins by combining related functions',
      D: 'Import all 15 functions as individual standalone KernelFunctions without plugin grouping — the Semantic Kernel planner handles all functions equally regardless of plugin structure',
    },
    answer: 'B',
    explanation: 'Semantic Kernel plugins are logical groupings: each plugin has a name and description that the kernel\'s planner uses to reason about which plugin to invoke for a task. A single plugin with 15 mixed functions is semantically confusing — the planner can\'t distinguish "document processing" from "email operations" at the plugin selection level. Split into 3 plugins with clear names and descriptions: DocumentPlugin ("handles document loading, parsing, and extraction"), CalendarPlugin ("manages calendar events and scheduling"), EmailPlugin ("sends, drafts, and reads emails"). The planner then selects the right plugin before choosing a function within it — dramatically improving planning accuracy.',
    keywords: ['Semantic Kernel', 'plugin', 'planner', 'single responsibility', 'function grouping'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: false,
    quality: 'preparto',
  },
  {
    id: 2908,
    domain: 2,
    domainName: 'Agent Development',
    topic: 'Scenario: Prompt Template Management',
    question: 'Your production agent has 12 prompt templates hardcoded as Python string constants across 8 files. The product team wants to A/B test prompt variations without code deployments. Select TWO architectural changes that enable runtime prompt management.',
    options: {
      A: 'Store prompts in a database or external config service (e.g., a prompt registry) with versioned entries — the agent loads the active prompt version at startup or per-request based on a feature flag',
      B: 'Use LangChain Hub or a similar prompt registry where prompts are stored as versioned artifacts, pulled by name+version at runtime — enables A/B testing by pointing different traffic segments to different versions',
      C: 'Move all prompts into a single Python constants file — centralization is sufficient for A/B testing since you can change one file per variant',
      D: 'Generate prompts dynamically using an LLM that is prompted to create prompts for each request — eliminates the need for static templates',
      E: 'Serialize all prompt templates to environment variables — the deployment team can update env vars without code deployments',
    },
    answer: 'AB',
    explanation: 'Option A (external prompt registry/DB): storing prompts as versioned database entries decouples prompt management from code deployment. A feature flag service routes traffic to variant A (prompt_v1) or variant B (prompt_v2). Option B (LangChain Hub or equivalent): LangChain Hub stores prompts as versioned artifacts with push/pull semantics — `hub.pull("my-org/extraction-prompt:v2")` at runtime, no code change. Both patterns enable the product team to update, version, and A/B test prompts without engineering involvement. Option C (single constants file) still requires a code deployment. Option D (LLM generates prompts) is expensive, slow, and unreliable. Option E (env vars) is unversioned, unauditable, and breaks for complex multi-line templates.',
    keywords: ['prompt registry', 'LangChain Hub', 'A/B testing', 'versioned prompts', 'feature flags'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 2909,
    domain: 2,
    domainName: 'Agent Development',
    topic: 'Scenario: NIM as Tool Endpoint',
    question: 'You want to replace your current OpenAI-hosted LLM in a LangChain agent with a self-hosted NVIDIA NIM running Llama-3.1-70B. The agent currently uses `ChatOpenAI(model="gpt-4o")`. What is the minimal code change required and why does it work?',
    options: {
      A: 'Replace with `ChatNVIDIA(model="meta/llama-3.1-70b-instruct", base_url="http://nim-host:8000/v1")` — NIM exposes an OpenAI-compatible API, so LangChain\'s ChatNVIDIA (or ChatOpenAI with base_url override) works with zero other changes',
      B: 'Rewrite the entire agent to use NVIDIA\'s proprietary inference SDK — NIM does not expose an OpenAI-compatible API and requires a custom client',
      C: 'Use `ChatOpenAI(base_url="http://nim-host:8000/v1", model="llama-3.1-70b")` — since NIM is OpenAI-API-compatible, you only need to change the base_url and model name, with no other code changes',
      D: 'Both A and C are correct — NIM exposes an OpenAI-compatible endpoint, and both ChatNVIDIA and ChatOpenAI with base_url override work',
    },
    answer: 'D',
    explanation: 'NVIDIA NIM exposes an OpenAI-compatible REST API at `/v1/chat/completions`. This means you can connect to NIM using either: (A) `ChatNVIDIA` (LangChain\'s NVIDIA-specific wrapper, which sets defaults for NVIDIA endpoints) or (C) `ChatOpenAI` with `base_url` pointing to the NIM host (any OpenAI-API-compatible framework works). Both require only changing 1-2 parameters — no agent logic changes, no tool redefinitions, no prompt rewrites. Option B is factually false — NIM\'s design goal is OpenAI API compatibility. This is the key advantage of NIM: drop-in replacement for any OpenAI-API-compatible framework.',
    keywords: ['NIM', 'OpenAI-compatible', 'ChatNVIDIA', 'base_url', 'Llama', 'drop-in replacement'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 2910,
    domain: 2,
    domainName: 'Agent Development',
    topic: 'Scenario: Agent Memory Patterns',
    question: 'Your conversational agent for a B2B SaaS platform needs three types of memory: (1) what was discussed in the current session, (2) the customer\'s account preferences set last month, (3) the general knowledge that "enterprise customers prefer formal language." Select TWO memory architectures that correctly map to these three requirements.',
    options: {
      A: 'Use in-memory buffer for (1), a persistent database (PostgreSQL keyed by customer_id) for (2), and a vector store with semantic search for (3)',
      B: 'Use a single Redis cache with TTLs: short TTL for (1), medium TTL for (2), and no TTL for (3)',
      C: 'Use episodic memory (in-context conversation buffer) for (1), semantic memory (persistent key-value store by entity) for (2), and procedural/semantic memory (vector store of general behavioral rules) for (3)',
      D: 'Store all three types in the system prompt — a long system prompt can hold session history, customer preferences, and general rules without separate memory systems',
      E: 'Use a memory library like mem0 that automatically classifies memories into episodic, semantic, and procedural categories and handles storage/retrieval transparently',
    },
    answer: 'AC',
    explanation: 'Option A correctly maps technical implementations to requirements: buffer/in-memory for short-lived session data (current session, clears on session end), persistent DB by customer_id for durable customer-specific preferences (survives across sessions, weeks/months), and vector store for general behavioral knowledge (retrieved by semantic similarity — "this customer is enterprise" → retrieves "enterprise customers prefer formal language"). Option C describes the same mapping using the cognitive memory taxonomy: episodic (current session events), semantic (entity-level facts about the customer), procedural/semantic (general behavioral rules). Both A and C are correct descriptions of the same architecture. Option B (Redis with TTLs) is oversimplified. Option D (system prompt) hits context limits for long histories. Option E (mem0) is a valid tool but a tool choice, not an architecture pattern.',
    keywords: ['episodic memory', 'semantic memory', 'procedural memory', 'memory taxonomy', 'vector store', 'mem0'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
];
