import { Question } from '../types';

export const domain1ExamQuestions: Question[] = [
  {
    id: 1901,
    domain: 1,
    domainName: 'Agent Architecture & Design',
    topic: 'Scenario: LangGraph Conditional Routing',
    question: 'Your LangGraph agent processes customer support tickets. After an LLM classifies the ticket, it must route to one of: billing_agent, technical_agent, or escalation_agent — but only escalate if the customer has contacted support more than 3 times in 30 days AND the issue is unresolved. Which LangGraph construct correctly implements this compound conditional?',
    options: {
      A: 'A single edge with a lambda checking both conditions, routing to escalation_agent if True, otherwise running both billing and technical agents in parallel',
      B: 'A conditional_edge from the classifier node with a routing function that reads both the classification output and a CRM lookup tool result from the shared state, returning the target node name as a string',
      C: 'Two separate conditional_edges — one for contact frequency, one for issue status — each independently routing to escalation_agent',
      D: 'A tool node that calls a decision LLM with the ticket context and CRM history, then an unconditional edge to whichever agent the decision LLM names',
    },
    answer: 'B',
    explanation: 'LangGraph conditional_edge takes a routing function that receives the current state and returns a node name string (or END). The key insight: the state can contain both the classifier output AND the CRM lookup result (populated by a prior tool node), so the routing function can evaluate the compound condition in one pass. Option A is wrong — you cannot fan-out and also conditionally route in the same edge. Option C creates a race condition where both conditions independently trigger escalation. Option D introduces an LLM call for a deterministic rule — wasteful and unreliable.',
    keywords: ['LangGraph', 'conditional_edge', 'routing function', 'state', 'compound condition'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 1902,
    domain: 1,
    domainName: 'Agent Architecture & Design',
    topic: 'Scenario: AgentIQ Observability Integration',
    question: 'Your multi-agent pipeline uses LangChain for two agents and a custom Python agent for a third. You need full workflow-level tracing across all three without rewriting any agent logic. Select TWO capabilities NVIDIA AgentIQ provides that make this possible.',
    options: {
      A: 'AgentIQ compiles all three agents into a single CUDA execution graph at startup, enabling GPU-accelerated tracing with zero Python overhead',
      B: 'AgentIQ provides framework-agnostic instrumentation wrappers that can wrap LangChain agents, LlamaIndex agents, and custom Python callables with the same decorator-based API',
      C: 'AgentIQ automatically replaces the underlying LLM in each agent with a faster quantized NIM endpoint, reducing tracing latency by eliminating the bottleneck',
      D: 'AgentIQ emits OpenTelemetry-compatible spans for every tool call, LLM invocation, and retrieval step — enabling export to Phoenix, Langfuse, or Weave without agent code changes',
      E: 'AgentIQ fine-tunes the agents in real-time using trace data to improve response quality after every 100 interactions',
    },
    answer: 'BD',
    explanation: 'AgentIQ (NVIDIA\'s agent observability toolkit) is framework-agnostic: (B) it wraps LangChain, LlamaIndex, CrewAI, Semantic Kernel, and custom Python agents with the same instrumentation API — no rewrite needed. (D) it emits OpenTelemetry spans that integrate directly with observability backends like Phoenix, Langfuse, and Weave. Option A is false — CUDA graphs are for tensor operations, not Python control flow tracing. Option C is false — AgentIQ does not swap LLM endpoints. Option E is false — AgentIQ observes, it does not fine-tune.',
    keywords: ['AgentIQ', 'OpenTelemetry', 'framework-agnostic', 'instrumentation', 'Phoenix', 'Langfuse'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 1903,
    domain: 1,
    domainName: 'Agent Architecture & Design',
    topic: 'Scenario: Dynamic Tool Registry',
    question: 'Your enterprise agent platform has 200+ tools across 12 business domains. During testing you notice the agent frequently selects wrong tools or hallucinates tool names that don\'t exist. Your architect proposes "dynamic tool loading." What does this correctly mean and how should it be implemented?',
    options: {
      A: 'Load all 200 tools at startup and use a BM25 keyword index to filter to the top 10 before injecting into the system prompt each turn',
      B: 'Embed user query → semantic search against embedded tool descriptions → inject only the top-K most relevant tools (K=5-10) into the system prompt for that specific turn, leaving all others out of context',
      C: 'Group tools into 12 domain bundles and inject the entire bundle matching the detected query domain — trading precision for recall',
      D: 'Cache the full tool list in the model\'s KV cache so the tool selection cost is paid once and amortized across all requests',
    },
    answer: 'B',
    explanation: 'Dynamic tool loading: embed tool descriptions offline → at inference time, embed the user query → cosine similarity search → retrieve top-K tools → inject only those K tools into the system prompt. This keeps the tool selection context small (5-10 tools instead of 200), dramatically improving LLM tool selection accuracy. Option A (BM25) misses semantic matches ("find customer" won\'t match "lookup_account_by_id"). Option C (domain bundles) can still inject 20-30 tools if a domain is large. Option D misunderstands KV caching — it caches token representations, not "available tools" as a runtime concept.',
    keywords: ['dynamic tool loading', 'semantic search', 'tool registry', 'context window', 'tool selection'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 1904,
    domain: 1,
    domainName: 'Agent Architecture & Design',
    topic: 'Scenario: Fan-Out Latency Optimization',
    question: 'Your research agent must: (1) search the web for 5 independent topics, (2) for each topic read the top 2 URLs, (3) synthesize all findings. Currently sequential execution takes 85 seconds. The architect wants to parallelize. Select TWO architectural changes that yield the maximum latency reduction.',
    options: {
      A: 'Parallelize all 5 web searches concurrently (fan-out), then for each search result parallelize the 2 URL reads — reducing search+read from sequential to max(search_i + max(read_i1, read_i2))',
      B: 'Use a faster LLM for the synthesis step only, since synthesis is the longest step',
      C: 'Cache web search results in Redis so repeated searches return instantly — converting search latency to cache lookup latency',
      D: 'Run all 5 searches AND all 10 URL reads in a single fan-out (total 15 concurrent operations), with synthesis gated on a fan-in that waits for all 15 to complete',
      E: 'Pre-fetch the 5 topics\' top URLs in a background job that runs before the user submits their query',
    },
    answer: 'AD',
    explanation: 'Option A: parallelizing searches and URL reads independently is correct — 5 searches in parallel take max(search_time), then within each search result the 2 URL reads also run in parallel. Option D goes further: treating all 15 I/O operations (5 searches + 10 reads) as independent and running them all concurrently is the maximum parallelism achievable — synthesis waits for the slowest of 15 operations rather than the sum. Together A+D describe the same maximal parallelism strategy. Option B misidentifies synthesis as the bottleneck (it\'s I/O). Option C helps with repeated identical queries, not first-time requests. Option E requires knowing the query topics in advance.',
    keywords: ['fan-out', 'fan-in', 'parallelism', 'async', 'latency optimization'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 1905,
    domain: 1,
    domainName: 'Agent Architecture & Design',
    topic: 'Scenario: Agent Loop Safeguards',
    question: 'Your coding agent is looping: it repeatedly calls a search tool with slightly varied queries ("Python async best practices", "Python async patterns", "asyncio best practices") without making progress. It has consumed 40 of your 50 tool-call budget. What combination of safeguards would have prevented this AND would handle it gracefully now?',
    options: {
      A: 'A hard tool-call limit (e.g., 50) combined with loop detection via query similarity hashing — if the last 3 queries have >85% cosine similarity, classify as stuck and surface a structured "stuck" signal to the orchestrator',
      B: 'Increase the tool-call budget to 200 — the agent is simply doing thorough research and the loop will resolve naturally',
      C: 'Kill the agent process after 60 seconds regardless of progress — timeout-based termination prevents infinite loops',
      D: 'Restart the agent from scratch with a different system prompt on every 10th tool call',
    },
    answer: 'A',
    explanation: 'Production agent safeguards need two layers: (1) a hard budget cap prevents runaway cost, and (2) loop detection via query similarity hashing catches stuck behavior early rather than waiting for the cap. When similarity of recent queries exceeds a threshold, emit a structured "I am stuck, need clarification on X" signal — this is far better than silent timeout (C, which discards partial work), increasing budget (B, which just delays the same failure), or restarting (D, which loses context and wastes prior tool calls). The stuck signal allows the orchestrator to escalate to a human or try a different sub-agent.',
    keywords: ['agent loop', 'loop detection', 'similarity hashing', 'tool budget', 'stuck signal'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 1906,
    domain: 1,
    domainName: 'Agent Architecture & Design',
    topic: 'Scenario: Multi-Agent Communication Protocol',
    question: 'You are designing a multi-agent system where a coordinator agent delegates to 4 specialist agents. Specialists sometimes need to share partial results with each other mid-execution. Select TWO communication patterns that are architecturally sound for this requirement.',
    options: {
      A: 'Direct peer-to-peer tool calls between specialist agents — each specialist has a "call_specialist" tool that invokes another specialist\'s API endpoint directly',
      B: 'Shared state store (Redis or in-memory dict in LangGraph state) where specialists write partial results to named keys that other specialists can read when needed',
      C: 'Route all inter-specialist communication through the coordinator, which acts as the message broker — specialists never talk directly, only through the coordinator\'s state',
      D: 'Use a publish-subscribe event bus where specialists emit events and subscribe to topics — decoupled communication without direct dependencies',
      E: 'Serialize all specialist execution — each specialist waits for the previous to complete before starting, then reads its full output',
    },
    answer: 'BD',
    explanation: 'Option B (shared state): in LangGraph, the shared state dict is exactly this — specialists can write partial results to state keys and other nodes can read them. This is the canonical LangGraph pattern for inter-agent data sharing. Option D (pub/sub event bus): for async multi-agent systems, a pub/sub bus decouples producers and consumers — a specialist emits "retrieval_complete" and any subscriber picks it up without tight coupling. Option A (direct peer calls) creates tight coupling and circular dependency risks. Option C (all through coordinator) is safe but creates a coordinator bottleneck for high-frequency communication. Option E (serialized) eliminates all parallelism benefits.',
    keywords: ['multi-agent', 'shared state', 'pub/sub', 'LangGraph state', 'communication protocol'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 1907,
    domain: 1,
    domainName: 'Agent Architecture & Design',
    topic: 'Scenario: Context Window Management',
    question: 'Your legal document analysis agent processes 200-page contracts. The full document exceeds the LLM\'s 128k context window. The agent needs to answer specific questions about clauses across the entire document. Which architectural pattern is most appropriate?',
    options: {
      A: 'Chunk the document into 4k token segments, embed each chunk, store in a vector database, then retrieve the top-K most relevant chunks per question and inject only those into the context window',
      B: 'Use a sliding window approach: process the document sequentially in overlapping 100k token windows, summarize each window, then answer questions from the summary chain',
      C: 'Request a larger context window model — the 128k limit is a hardware constraint that the cloud provider can raise on demand',
      D: 'Split the document into sections and run a separate agent instance per section, then merge all answers with a final synthesis agent',
    },
    answer: 'A',
    explanation: 'RAG (Retrieval-Augmented Generation) with vector search is the correct pattern for targeted question answering over long documents. Embed chunks → at question time, retrieve semantically relevant chunks → inject only those into context. This scales to documents of any size, is precise (retrieves relevant clauses, not adjacent ones), and supports multiple questions efficiently. Option B (sliding window summary) loses fine-grained clause details in summarization — bad for legal precision. Option C is incorrect — larger context windows don\'t exist on demand. Option D (per-section agents) works but creates unnecessary agent overhead and misses cross-section clause references.',
    keywords: ['RAG', 'vector database', 'chunking', 'context window', 'legal agent'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 1908,
    domain: 1,
    domainName: 'Agent Architecture & Design',
    topic: 'Scenario: NIM Tool Endpoint Architecture',
    question: 'Your agent platform uses NVIDIA NIM to serve the underlying LLM. You need the NIM endpoint to behave as a tool provider — your orchestrator agent calls NIM for reasoning but also needs to call NIM-served specialized models (a code model, a math model) as tools. Select TWO architectural decisions that correctly leverage NIM for this pattern.',
    options: {
      A: 'Deploy separate NIM containers for the reasoning model, code model, and math model — each exposes an OpenAI-compatible /v1/chat/completions endpoint that the orchestrator calls as a structured tool',
      B: 'Use a single NIM deployment with model routing middleware that selects the target model based on a "model" parameter in the request header',
      C: 'Configure NIM\'s built-in multi-model routing to serve all three models from a single GPU, eliminating the need for separate containers',
      D: 'Wrap each NIM endpoint as a LangChain Tool or LangGraph tool node — the orchestrator selects which specialized NIM to call based on task type, using standard tool-calling syntax',
      E: 'Fine-tune the reasoning model to absorb both code and math capabilities, deploying a single NIM that handles all tasks without tool calling',
    },
    answer: 'AD',
    explanation: 'Option A: NIM\'s OpenAI-compatible API makes each NIM deployment a drop-in replacement for any OpenAI-API-compatible tool call. Running separate NIM containers per model (reasoning, code, math) is the correct production pattern — each can be independently scaled and updated. Option D: wrapping NIM endpoints as LangChain Tools / LangGraph tool nodes is exactly how the orchestrator calls them as tools — the tool definition specifies the NIM URL and the orchestrator\'s function-calling syntax routes to the right NIM. Option B is not a NIM built-in feature. Option C is false — NIM does not have built-in multi-model routing within a single container. Option E reduces flexibility and requires expensive retraining.',
    keywords: ['NIM', 'tool endpoint', 'OpenAI-compatible', 'LangChain Tool', 'orchestrator'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 1909,
    domain: 1,
    domainName: 'Agent Architecture & Design',
    topic: 'Scenario: Event-Driven Agent Architecture',
    question: 'Your inventory management agent must react to three event types: (1) stock_level_drop below threshold, (2) supplier_price_change, (3) demand_forecast_update — all arriving asynchronously from different systems at different frequencies. The current polling-based design checks each source every 5 minutes causing 4.5-minute average lag. What is the correct architectural fix?',
    options: {
      A: 'Reduce polling interval from 5 minutes to 30 seconds across all three sources',
      B: 'Implement an event-driven architecture: each source publishes events to a message queue (e.g., Kafka or Redis Streams); the agent subscribes and triggers immediately on event receipt, reducing reaction latency from minutes to seconds',
      C: 'Deploy three separate polling agents, one per event type, each polling its source every 60 seconds, reducing average lag to 30 seconds per type',
      D: 'Use webhooks from each source system to push events directly to the agent\'s HTTP endpoint, eliminating polling entirely',
    },
    answer: 'B',
    explanation: 'Event-driven architecture with a message queue is the correct pattern for multi-source async event processing. A message queue (Kafka, Redis Streams, RabbitMQ) decouples event producers from the agent consumer: sources publish when events occur, the agent subscribes and processes immediately. This eliminates polling lag entirely. Option A (faster polling) reduces lag but still wastes resources on empty polls and doesn\'t scale. Option C (3 agents) reduces lag but multiplies resource usage and creates coordination complexity. Option D (webhooks) is also valid but tightly couples sources to the agent\'s HTTP endpoint — less resilient to agent downtime than a durable queue.',
    keywords: ['event-driven', 'message queue', 'Kafka', 'Redis Streams', 'async', 'polling'],
    difficulty: 'hard',
    type: 'single',
    answerCount: 1,
    isScenario: true,
    quality: 'preparto',
  },
  {
    id: 1910,
    domain: 1,
    domainName: 'Agent Architecture & Design',
    topic: 'Scenario: Orchestrator Failure Isolation',
    question: 'Your orchestrator agent delegates to 5 specialist agents. During load testing, when the billing_agent becomes slow (p99 latency 45s), the orchestrator blocks waiting for it — causing all other specialties to queue behind billing requests and the entire system to degrade. Select TWO architectural patterns that prevent this cascade failure.',
    options: {
      A: 'Set an independent timeout per specialist agent call (e.g., 10s for billing_agent) with a circuit breaker that opens after 3 consecutive timeouts — failing fast with a fallback response rather than blocking',
      B: 'Run each specialist agent invocation in its own async task with its own timeout — orchestrator fans out all specialists concurrently and collects results independently, so a slow billing_agent only delays billing responses, not the others',
      C: 'Increase the orchestrator\'s global timeout from 30s to 120s to accommodate the slow billing_agent',
      D: 'Add a health check endpoint to billing_agent and poll it every second — if unhealthy, skip billing delegation entirely',
      E: 'Deploy billing_agent on a dedicated GPU instance to improve its latency',
    },
    answer: 'AB',
    explanation: 'Option A (circuit breaker + timeout): the circuit breaker pattern prevents cascade by failing fast — after N timeouts, the orchestrator stops calling billing_agent immediately instead of waiting. This bounds the blast radius. Option B (async fan-out with per-task timeouts): running specialist calls as independent async tasks means a slow billing_agent only blocks its own task — other specialists complete and return independently. Together, A+B provide both proactive isolation (per-call timeouts) and structural isolation (async fan-out). Option C (longer global timeout) makes the problem worse — now ALL requests wait up to 120s. Option D (health check polling) adds overhead and has a 1-second detection gap. Option E addresses the symptom, not the architectural failure mode.',
    keywords: ['circuit breaker', 'async fan-out', 'timeout', 'failure isolation', 'orchestrator'],
    difficulty: 'hard',
    type: 'multi',
    answerCount: 2,
    isScenario: true,
    quality: 'preparto',
  },
];
