import { Question } from '../types';

export const domain5cQuestions: Question[] = [
  { id: 5041, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Spatial Reasoning', difficulty: 'hard', keywords: ['spatial', 'layout', 'navigation', 'reasoning'],
    question: 'AI agents performing spatial reasoning tasks (navigation, layout analysis) benefit most from:',
    options: { A: 'Larger language model with more parameters', B: 'Multimodal inputs combining visual maps/images with structured coordinate representations for precise spatial understanding', C: 'Verbal descriptions of spatial layouts only', D: 'Spatial reasoning requires robotic embodiment' },
    answer: 'B', explanation: 'Spatial reasoning: pure text ("go left then forward") is ambiguous. Multimodal (image + coordinates) provides precise spatial grounding. Structured coordinate systems (x,y) enable mathematical reasoning about positions and distances.' },

  { id: 5042, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Abductive Reasoning', difficulty: 'hard', keywords: ['abductive reasoning', 'inference to best explanation', 'hypothesis', 'diagnosis'],
    question: 'Abductive reasoning in AI agents involves:',
    options: { A: 'Reasoning backward from effects to causes — generating the most plausible explanation for observed evidence', B: 'Deductive reasoning starting from axioms', C: 'Inductive reasoning from multiple examples', D: 'Abducting data from external sources' },
    answer: 'A', explanation: 'Abductive reasoning: "The system is down AND errors show timeout → most likely explanation: database unreachable." Used in diagnosis, root cause analysis, and scientific hypothesis generation.' },

  { id: 5043, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Narrative Memory', difficulty: 'medium', keywords: ['narrative', 'story', 'coherence', 'memory'],
    question: 'Narrative memory in AI agents maintains:',
    options: { A: 'A list of all past actions in chronological order', B: 'A coherent story of agent activities — context, motivations, and outcomes — enabling meaningful reference to past work', C: 'Fictional stories generated by the agent', D: 'Only the most recent interaction' },
    answer: 'B', explanation: 'Narrative memory: "Last week I was helping with the Q3 report. We found data quality issues in the sales figures. The finance team was notified." Coherent narrative vs. raw action logs enables natural cross-session context.' },

  { id: 5044, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Plan Repair', difficulty: 'medium', keywords: ['plan repair', 'replanning', 'failure', 'adaptation'],
    question: 'Plan repair (vs full replanning) in agent systems is preferable when:',
    options: { A: 'The original plan completely failed', B: 'Only part of the plan failed — repair the failed step and adjust downstream steps rather than regenerating the entire plan from scratch', C: 'Replanning is always faster than plan repair', D: 'Plan repair is only used in classical AI planning, not LLM agents' },
    answer: 'B', explanation: 'Plan repair: if step 3 of a 10-step plan fails, don\'t restart from step 1. Diagnose step 3 failure → generate alternative for step 3 → check if steps 4-10 still valid or need adjustment. Faster than full replanning when partial progress is valid.' },

  { id: 5045, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Attention and Focus', difficulty: 'medium', keywords: ['selective attention', 'relevance', 'filtering', 'priority'],
    question: 'Selective attention in AI agents determines:',
    options: { A: 'Which words the model attends to in its self-attention layers', B: 'Which information in the context is most relevant to the current task — filtering noise and prioritizing relevant signals for decision-making', C: 'How much attention the agent gives to user requests', D: 'Attention to detail in formatted outputs' },
    answer: 'B', explanation: 'Selective attention mechanisms: relevance scoring of context elements (retrieved documents, conversation history items) → weight higher-relevance items more in prompt → agent focuses on what matters, not everything available.' },

  { id: 5046, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Common Sense Reasoning', difficulty: 'medium', keywords: ['common sense', 'world knowledge', 'implicit', 'reasoning'],
    question: 'Common sense reasoning gaps in LLM agents appear when:',
    options: { A: 'Agents are asked questions outside their training data', B: 'Agents fail to apply implicit world knowledge that humans take for granted (physical laws, social norms, basic causality)', C: 'Agents lack commonsense about their own limitations', D: 'Common sense gaps only appear in smaller models' },
    answer: 'B', explanation: 'Common sense gaps: LLMs may not apply "objects fall if unsupported" or "people feel cold in winter" without explicit context. Mitigation: chain-of-thought prompting to surface implicit reasoning, commonsense knowledge bases (ConceptNet).' },

  { id: 5047, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Decision Trees in Planning', difficulty: 'medium', keywords: ['decision tree', 'policy tree', 'branching', 'conditional'],
    question: 'Policy trees for agent planning encode:',
    options: { A: 'Machine learning decision trees for classification', B: 'Conditional action policies — "if condition A, take action X; if condition B, take action Y" — providing interpretable, auditable decision logic', C: 'Tree-structured prompt templates', D: 'Hierarchical organization of agent tools' },
    answer: 'B', explanation: 'Policy trees: explicit conditional logic for agent decisions. Customer service policy tree: "Is the customer asking about billing? → billing_agent. Is it a technical issue? → tech_support. Else → general_agent." Auditable, testable, and easily updated.' },

  { id: 5048, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Multi-Step Memory Retrieval', difficulty: 'hard', keywords: ['multi-hop', 'chain', 'retrieval', 'reasoning'],
    question: 'Multi-hop memory retrieval for complex queries involves:',
    options: { A: 'Jumping between multiple memory databases', B: 'Sequential retrieval where the answer to one sub-question informs the next retrieval step — enabling reasoning chains across stored memories', C: 'Retrieving multiple copies of the same memory', D: 'Distributed retrieval across multiple servers' },
    answer: 'B', explanation: 'Multi-hop: "Who is the CEO of the company that acquired Acme Corp?" → retrieve: "Acme Corp was acquired by GlobalTech" → retrieve: "GlobalTech CEO is Jane Smith" → answer. Each retrieval informs the next query.' },

  { id: 5049, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Confidence Calibration', difficulty: 'hard', keywords: ['confidence', 'uncertainty', 'epistemic', 'aleatoric'],
    question: 'Epistemic vs aleatoric uncertainty in AI agents refers to:',
    options: { A: 'Uncertainty about epistemological vs algorithmic knowledge', B: 'Epistemic: uncertainty due to lack of knowledge (reducible with more data); Aleatoric: irreducible randomness in the environment', C: 'Two levels of confidence scoring', D: 'Uncertainty in classical vs quantum computing contexts' },
    answer: 'B', explanation: 'Epistemic uncertainty: "I don\'t know enough about this domain" → can be reduced by providing more information. Aleatoric: "this outcome is inherently random" → can\'t be reduced. Agents should distinguish: "I don\'t know" vs "nobody can know for certain."' },

  { id: 5050, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Thought Experiments', difficulty: 'hard', keywords: ['counterfactual', 'simulation', 'mental model', 'what-if'],
    question: 'Mental simulation in AI planning enables agents to:',
    options: { A: 'Simulate the mental state of users they are helping', B: 'Reason about hypothetical futures ("what would happen if I took action X?") before committing to real-world actions', C: 'Run Monte Carlo simulations using the model\'s parameters', D: 'Mental simulation requires external simulation software' },
    answer: 'B', explanation: 'Mental simulation: "If I delete this file, it will be permanently lost → the user may need it later → I should ask for confirmation first." Agent reasons about downstream consequences before acting, avoiding irreversible mistakes.' },

  { id: 5051, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Task Decomposition Strategies', difficulty: 'medium', keywords: ['decomposition', 'subtask', 'dependency', 'parallel'],
    question: 'Identifying parallelizable vs sequential subtasks in agent planning:',
    options: { A: 'All subtasks should be executed in parallel for speed', B: 'Subtasks with no data dependencies can run in parallel; dependent subtasks must be sequential — maximizing parallelism reduces total execution time', C: 'Sequential execution is always safer than parallel', D: 'Task decomposition doesn\'t impact agent performance' },
    answer: 'B', explanation: 'Dependency analysis: "search web" and "search internal docs" have no dependency → parallel. "Synthesize results" depends on both searches → sequential after both complete. Parallel execution of independent tasks saves significant wall-clock time.' },

  { id: 5052, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Prospective Memory', difficulty: 'medium', keywords: ['prospective memory', 'reminder', 'future intention', 'scheduled'],
    question: 'Prospective memory in AI agents enables:',
    options: { A: 'Memory about future events that haven\'t happened yet', B: 'Remembering to perform future actions — "check back in 1 hour if no response received" — persisting intentions across agent invocations', C: 'Looking prospectively at all possible futures simultaneously', D: 'Memory about prospective (potential) users of the system' },
    answer: 'B', explanation: 'Prospective memory: "User asked me to remind them about meeting at 3pm → persist this intention → at 2:45pm, trigger reminder action." Requires durable storage of future intentions and time-based triggers separate from episodic memory.' },

  { id: 5053, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Belief Revision', difficulty: 'hard', keywords: ['belief revision', 'update', 'contradiction', 'AGM'],
    question: 'Belief revision in AI agents is triggered when:',
    options: { A: 'The agent changes its beliefs randomly for exploration', B: 'New information contradicts existing beliefs — the agent must determine which beliefs to update or discard based on reliability and recency', C: 'The agent revises its outputs after user feedback', D: 'Belief revision is only for formal logic systems' },
    answer: 'B', explanation: 'Belief revision: agent believes "Server X is online" (from 1 hour ago) but monitoring alert says "Server X is down" → update belief based on recency and source reliability. AGM framework: minimal change to belief set that accommodates new information.' },

  { id: 5054, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Cognitive Load Management', difficulty: 'medium', keywords: ['cognitive load', 'token budget', 'selective compression', 'focus'],
    question: 'Managing cognitive load in AI agents through context window budgeting involves:',
    options: { A: 'Reducing the quality of responses to save tokens', B: 'Allocating token budget strategically: more tokens for complex reasoning, fewer for simple retrieval — matching cognitive resources to task complexity', C: 'Always using the maximum possible context length', D: 'Cognitive load management only applies to human-facing interfaces' },
    answer: 'B', explanation: 'Token budget allocation: system prompt (300 tokens), task context (500), conversation history (1000), retrieved context (2000), reasoning space (1000), response (500). Adjust per task: simple queries need less reasoning space, complex tasks need more.' },

  { id: 5055, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Inference Patterns', difficulty: 'medium', keywords: ['inductive', 'deductive', 'abductive', 'reasoning modes'],
    question: 'An agent using inductive reasoning generates:',
    options: { A: 'Conclusions guaranteed to be true if premises are true', B: 'Generalizations from specific examples — "all cases I\'ve seen have property X, therefore X is likely a general rule"', C: 'The best explanation for observed phenomena', D: 'Mathematical proofs from axioms' },
    answer: 'B', explanation: 'Inductive reasoning: pattern recognition from examples. "Users from Europe asking about tax questions always need VAT information → create a rule: European tax queries → include VAT context." Probabilistic conclusions, not certainties.' },

  { id: 5056, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Agent Self-Improvement', difficulty: 'hard', keywords: ['self-improvement', 'reflection', 'iteration', 'meta-learning'],
    question: 'Reflexion (Shinn et al.) enables agents to self-improve by:',
    options: { A: 'Reflecting on model weights to identify improvements', B: 'Converting feedback from failed task attempts into verbal self-reflections stored in episodic memory and used to guide future attempts', C: 'Automatically retraining the model on failed examples', D: 'Reflection is a purely philosophical concept not applicable to AI' },
    answer: 'B', explanation: 'Reflexion: failed attempt → LLM generates reflection ("I failed because I didn\'t check input validation first") → store reflection in memory → next attempt loads past reflections → agent avoids same mistakes. Verbal RL without weight updates.' },

  { id: 5057, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Memory Indexing', difficulty: 'medium', keywords: ['indexing', 'metadata', 'retrieval', 'organization'],
    question: 'Effective indexing of agent memories enables:',
    options: { A: 'Faster storage of new memories', B: 'Efficient retrieval by multiple dimensions: time, topic, context, entities — finding relevant memories without scanning all stored information', C: 'Indexing memories by importance score only', D: 'Memory indexing is handled automatically by vector databases' },
    answer: 'B', explanation: 'Multi-dimensional memory indexing: time (recent), topic (semantic similarity), entity (what entities were involved), context (what task was being performed). Rich indexing → precise retrieval of "what do I remember about Project X from last month?"' },

  { id: 5058, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Semantic Parsing', difficulty: 'hard', keywords: ['semantic parsing', 'logical form', 'AMR', 'structured'],
    question: 'Semantic parsing of natural language into structured representations helps agents by:',
    options: { A: 'Parsing HTML semantics from web pages', B: 'Converting natural language ("find meetings between Alice and Bob in April") to executable logical forms that can be precisely computed', C: 'Improving grammar checking in agent outputs', D: 'Semantic parsing is only needed for SQL query generation' },
    answer: 'B', explanation: 'Semantic parsing: NL → structured form. "Find emails from John about the budget" → {action: search, source: email, from: John, topic: budget}. Precise, executable, auditable. Enables deterministic tool execution from NL instructions.' },

  { id: 5059, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Transfer of Knowledge', difficulty: 'medium', keywords: ['transfer learning', 'domain adaptation', 'knowledge transfer', 'new domain'],
    question: 'Transfer of reasoning skills across domains in AI agents is enabled by:',
    options: { A: 'Directly copying weights between domain-specific models', B: 'General reasoning capabilities (abstract pattern recognition, logical inference) that transfer regardless of domain content', C: 'Transfer learning only applies to vision models', D: 'Domain-specific knowledge cannot be transferred between agents' },
    answer: 'B', explanation: 'Cross-domain transfer: agent trained on legal reasoning can apply analogical reasoning skills to medical research ("this article structure is similar to precedent analysis"). General reasoning skills transfer; domain facts don\'t.' },

  { id: 5060, domain: 5, domainName: 'Cognition, Planning & Memory', topic: 'Interleaved Planning and Acting', difficulty: 'hard', keywords: ['interleaved', 'online planning', 'replanning', 'dynamic'],
    question: 'Interleaved planning and acting (vs plan-then-execute) enables:',
    options: { A: 'Faster execution by planning while acting', B: 'Adapting plans in response to real-world feedback — observations from each action inform and update subsequent planning steps', C: 'Interleaving is only for real-time robotic systems', D: 'No difference from pure plan-then-execute in LLM contexts' },
    answer: 'B', explanation: 'Interleaved planning: after each action, observe result → replan remaining steps based on new information. vs. Plan-then-execute: plan all steps upfront → execute rigidly even if conditions change. Interleaved handles dynamic, uncertain environments.' },
];
