import { Question } from '../types';

// Reconstructed from questions the user got wrong repeatedly on Certiq mock exams.
// Original Certiq answer options were not captured, so options/answer/explanation
// here are AI-authored best-effort recreations for extra drilling, not verbatim Certiq text.
export const flaggedQuestions: Question[] = [
  { id: 20001, domain: 2, domainName: 'Agent Development', topic: 'Tool/API Integration', difficulty: 'medium', keywords: ['API', 'logs', 'metadata', 'structured data'], verified: false, recurrenceCount: 2,
    question: 'An agent manages tasks through a service management API. The API returns detailed event logs containing both metadata and structured data. What is the most prudent approach for the agent to interpret and process this data correctly?',
    options: { A: 'Treat the entire log payload as unstructured text and extract fields using regex', B: 'Parse the response against a defined schema, separating metadata from structured payload fields before acting on them', C: 'Ignore metadata and only process the first structured field found', D: 'Convert the entire log to a summary string using an LLM call before parsing' },
    answer: 'B', explanation: 'Schema-aware parsing that explicitly separates metadata (timestamps, IDs, log levels) from the structured payload ensures the agent acts on validated, correctly-typed fields rather than guessing structure from raw text.' },

  { id: 20002, domain: 3, domainName: 'Evaluation and Tuning', topic: 'Fine-tuning for Reliability', difficulty: 'medium', keywords: ['fine-tuning', 'factual reliability', 'legal', 'RAG'], verified: false, recurrenceCount: 1,
    question: 'A deployed legal assistant performs well overall but occasionally repeats incorrect legal terms. Which tuning method would best improve its factual reliability?',
    options: { A: 'Increase the temperature to add response diversity', B: 'Supervised fine-tuning on a curated, verified legal corpus combined with retrieval grounding (RAG) for citations', C: 'Apply prompt-only few-shot examples with no additional grounding', D: 'Increase the max token output limit' },
    answer: 'B', explanation: 'Repeated factual errors on domain terms indicate a knowledge/grounding gap. Supervised fine-tuning on verified legal text plus RAG grounding anchors outputs to correct, sourced terminology rather than relying on parametric memory alone.' },

  { id: 20003, domain: 6, domainName: 'Knowledge Integration and Data Handling', topic: 'RAG Fusion', difficulty: 'hard', keywords: ['RAG Fusion', 'reciprocal rank fusion', 'chunk combination'], verified: false, recurrenceCount: 2,
    question: 'You are building a RAG system that uses RAG Fusion. Which approach is most effective for determining how to combine information from multiple retrieved chunks?',
    options: { A: 'Concatenate all chunks in retrieval order with no re-ranking', B: 'Generate multiple query variations, retrieve per-query result sets, then merge and re-rank using Reciprocal Rank Fusion (RRF)', C: 'Randomly sample a fixed number of chunks regardless of relevance score', D: 'Keep only the single top-ranked chunk from the original query' },
    answer: 'B', explanation: 'RAG Fusion generates query variants, retrieves results for each, and fuses the ranked lists (typically via Reciprocal Rank Fusion) so chunks consistently ranked high across multiple query framings surface to the top.' },

  { id: 20004, domain: 4, domainName: 'Deployment and Scaling', topic: 'GPU Resource Allocation', difficulty: 'hard', keywords: ['GPU utilization', 'A100', 'H100', 'Llama Nemotron'], verified: false, recurrenceCount: 2, type: 'multi', answerCount: 2,
    question: 'When evaluating GPU utilization inefficiencies deploying Llama Nemotron models across A100 and H100 clusters, which approaches help identify optimal resource allocation strategies? (Choose two.)',
    options: { A: 'Profile per-request GPU memory and compute utilization to detect underutilized batch sizes', B: 'Assign all workloads to H100s regardless of model size to guarantee performance', C: 'Benchmark throughput/latency per GPU generation to right-size model placement (e.g., smaller models on A100, larger/latency-critical on H100)', D: 'Disable dynamic batching to simplify monitoring' },
    answer: 'A,C', explanation: 'Identifying inefficiency requires profiling actual utilization (batch size, memory, compute) and benchmarking workload-to-hardware fit, so models are placed on the GPU generation that matches their compute/latency needs rather than defaulting to the most powerful hardware for everything.' },

  { id: 20005, domain: 8, domainName: 'Reliability and Error Handling', topic: 'Diagnosing Agent Errors', difficulty: 'medium', keywords: ['financial assistant', 'diagnosis', 'root cause'], verified: false, recurrenceCount: 2,
    question: 'After deploying a financial assistant agent, users report occasional inconsistencies in how transactions are categorized. What is the best first step for diagnosing the issue?',
    options: { A: 'Immediately retrain the model on new categorization data', B: 'Review logged traces of the categorization decisions (inputs, retrieved context, and reasoning) to isolate where inconsistency originates', C: 'Restart the agent service to clear any cached state', D: 'Add a disclaimer to the UI about possible errors' },
    answer: 'B', explanation: 'Before changing the model or data, you need to isolate the root cause via trace/log review — inconsistency could stem from ambiguous inputs, retrieval variance, or prompt non-determinism, and each has a different fix.' },

  { id: 20006, domain: 9, domainName: 'Safety, Ethics, and Compliance', topic: 'Semantic Guardrails', difficulty: 'medium', keywords: ['semantic guardrails', 'RAG', 'safety'], verified: false, recurrenceCount: 5,
    question: 'What is the primary purpose of implementing semantic guardrails within a RAG system?',
    options: { A: 'To reduce retrieval latency by caching embeddings', B: 'To detect and block unsafe, irrelevant, or policy-violating queries and generated responses based on their meaning, not just keyword matching', C: 'To improve embedding model accuracy through fine-tuning', D: 'To compress the context window sent to the LLM' },
    answer: 'B', explanation: 'Semantic guardrails evaluate the meaning/intent of queries and generated content (via classifiers or embedding similarity to unsafe examples) to catch violations that keyword filters would miss, protecting against unsafe or off-policy outputs.' },

  { id: 20007, domain: 9, domainName: 'Safety, Ethics, and Compliance', topic: 'RAGAS for Guardrails', difficulty: 'hard', keywords: ['RAGAS', 'safety checks', 'agentic AI'], verified: false, recurrenceCount: 4,
    question: 'Which statement accurately describes how RAGAS (Retrieval Augmented Generation Assessment) can be used for implementing safety checks and guardrails in agentic AI applications?',
    options: { A: 'RAGAS replaces the need for human review entirely once deployed', B: 'RAGAS provides reference-free metrics (e.g., faithfulness, answer relevance, context precision) that can be run continuously to flag hallucinated or ungrounded outputs before they reach users', C: 'RAGAS is only usable at training time, not in production monitoring', D: 'RAGAS guarantees regulatory compliance automatically' },
    answer: 'B', explanation: 'RAGAS metrics like faithfulness and context precision can be computed without ground-truth answers, making them suitable as automated, continuous guardrail checks that flag low-faithfulness or poorly-grounded responses in production pipelines.' },

  { id: 20008, domain: 10, domainName: 'Human-AI Interaction and Oversight', topic: 'Multi-Agent Oversight UI', difficulty: 'hard', keywords: ['supply chain', 'UI design', 'human oversight', 'multi-agent'], verified: false, recurrenceCount: 3,
    question: 'A logistics company\'s multi-agent supply chain system needs managers with varying technical expertise to monitor AI decisions, understand reasoning, and intervene quickly. Which UI design approach BEST supports effective human oversight?',
    options: { A: 'A single raw log stream of all agent actions and internal states', B: 'A tiered/layered dashboard: high-level summary and alerts for quick decisions, with drill-down views exposing detailed reasoning and data for technical users', C: 'A command-line interface requiring scripted queries for all data access', D: 'Static weekly reports with no real-time visibility' },
    answer: 'B', explanation: 'A layered interface lets non-technical managers get quick, actionable summaries while still allowing technical users to drill into detailed reasoning — meeting both "quick decision-making" and "detailed insight" requirements simultaneously.' },

  { id: 20009, domain: 8, domainName: 'Reliability and Error Handling', topic: 'Tool/API Reliability Analysis', difficulty: 'medium', keywords: ['tool integration', 'API reliability', 'performance'], verified: false, recurrenceCount: 2, type: 'multi', answerCount: 2,
    question: 'When evaluating an agent\'s integration with external tools and APIs for data retrieval and action execution, which analysis approaches effectively identify reliability and performance issues? (Choose two.)',
    options: { A: 'Track API call success/failure rates, latency distributions, and retry/timeout patterns over time', B: 'Assume all third-party APIs behave identically and skip per-tool monitoring', C: 'Run structured failure-injection/chaos testing against tool calls to observe agent fallback behavior', D: 'Only test tools once before initial deployment' },
    answer: 'A,C', explanation: 'Continuous monitoring of call-level metrics (latency, failure rate, retries) combined with deliberate failure-injection testing reveals both steady-state reliability issues and how gracefully the agent degrades under tool failures.' },

  { id: 20010, domain: 4, domainName: 'Deployment and Scaling', topic: 'Fleet-Scale Observability', difficulty: 'hard', keywords: ['autonomous vehicle', 'fleet monitoring', 'GPU', 'predictive'], verified: false, recurrenceCount: 2,
    question: 'An autonomous vehicle company runs a multi-agent AI system across its fleet and needs fleet-wide monitoring of GPU utilization, inference times, and memory, correlated with driving conditions, plus predictive safety alerts. Which monitoring approach BEST meets these requirements?',
    options: { A: 'Centralized time-series observability platform aggregating per-vehicle telemetry with correlation analytics and anomaly-detection/predictive models for safety-relevant metrics', B: 'Manual periodic log review by engineers after incidents occur', C: 'Local-only logging on each vehicle with no central aggregation', D: 'A single fleet-wide average metric reported daily' },
    answer: 'A', explanation: 'Safety-critical fleet-scale systems need real-time, centralized aggregation of per-vehicle telemetry with correlation and predictive analytics — this is the only option that supports proactive (not just reactive) safety issue detection across the fleet.' },

  { id: 20011, domain: 4, domainName: 'Deployment and Scaling', topic: 'Cost & Scaling Optimization', difficulty: 'medium', keywords: ['scaling costs', 'peak hours', 'customer service', 'bottlenecks'], verified: false, recurrenceCount: 2, type: 'multi', answerCount: 2,
    question: 'A multi-agent customer service system has unpredictable scaling costs and performance bottlenecks during peak hours. Which analysis approaches effectively identify optimization opportunities for both infrastructure efficiency and service reliability? (Choose two.)',
    options: { A: 'Analyze request/traffic patterns to right-size autoscaling policies and pre-warm capacity ahead of predictable peaks', B: 'Profile per-agent latency and resource consumption to find bottleneck agents/tools driving cost and slow responses', C: 'Fix the infrastructure at maximum peak capacity permanently', D: 'Disable autoscaling to keep costs constant regardless of load' },
    answer: 'A,B', explanation: 'Traffic-pattern analysis enables proactive, cost-efficient autoscaling, while per-agent profiling pinpoints which components actually cause bottlenecks — together addressing both the cost unpredictability and the reliability issue.' },

  { id: 20012, domain: 3, domainName: 'Evaluation and Tuning', topic: 'LLM-as-a-Judge', difficulty: 'medium', keywords: ['LLM-as-a-judge', 'synthetic QA', 'evaluation'], verified: false, recurrenceCount: 1,
    question: 'You are using an LLM-as-a-Judge to evaluate a RAG pipeline. What is the primary benefit of synthetically generating question-answer pairs rather than relying solely on human-created test cases?',
    options: { A: 'Synthetic pairs are always more accurate than human-labeled ones', B: 'It enables scalable, low-cost generation of large, diverse evaluation sets covering edge cases that would be expensive or slow to hand-author', C: 'It removes the need for any human review of the evaluation pipeline', D: 'It eliminates the need for a judge model' },
    answer: 'B', explanation: 'Synthetic QA generation scales evaluation coverage cheaply and quickly, including edge cases and long-tail scenarios that would take significant human effort to curate manually.' },

  { id: 20013, domain: 5, domainName: 'Cognition, Planning, and Memory', topic: 'Multi-Agent Reasoning Architecture', difficulty: 'hard', keywords: ['oil and gas', 'multi-agent', 'chain-of-thought', 'memory persistence'], verified: false, recurrenceCount: 2,
    question: 'A multi-agent system for drilling operations has agents for subsurface modeling, risk analysis, and resource allocation that must share operational context, reason through interdependent steps, and justify decisions transparently, with memory persistence and chain-of-thought prompting. Which implementation best supports this design?',
    options: { A: 'Independent agents with no shared state, each using isolated single-turn prompts', B: 'An orchestrated multi-agent architecture with a shared memory/state store, explicit sequential planning (e.g., graph-based workflow), and CoT prompting logged at each step for traceability', C: 'A single monolithic prompt containing all three domains\' logic', D: 'Agents communicating only via unstructured free-text messages with no persisted state' },
    answer: 'B', explanation: 'Shared context, sequential interdependent reasoning, and transparent justification require an orchestrated architecture with persistent shared memory and explicit, logged chain-of-thought steps — not isolated agents or a single monolithic prompt.' },

  { id: 20014, domain: 5, domainName: 'Cognition, Planning, and Memory', topic: 'Memory Architecture', difficulty: 'easy', keywords: ['memory architecture', 'conversation flow', 'user preferences'], verified: false, recurrenceCount: 1,
    question: 'Which memory architecture is most appropriate for an agent that must track conversation flow and remember user preferences across multiple interactions?',
    options: { A: 'No memory — treat every turn as stateless', B: 'A combination of short-term (working/conversation buffer) memory for flow and long-term persistent memory (e.g., a user profile/vector or key-value store) for preferences across sessions', C: 'Only long-term memory, discarding the current conversation buffer', D: 'A single fixed-size prompt with no distinction between memory types' },
    answer: 'B', explanation: 'Conversation flow needs short-term/working memory scoped to the session, while user preferences need long-term memory persisted across sessions — an effective agent combines both memory types rather than relying on just one.' },

  { id: 20015, domain: 1, domainName: 'Agent Architecture & Design', topic: 'ReAct Pattern', difficulty: 'medium', keywords: ['ReAct', 'reasoning', 'acting', 'tool use'], verified: false, recurrenceCount: 1,
    question: 'In a ReAct (Reasoning-Acting) agent architecture, what is the correct sequence of operations when the agent encounters a complex multi-step problem requiring external tool usage?',
    options: { A: 'Act first, then reason about whether the action was needed', B: 'Reason about the sub-goal → decide and take an action (e.g., tool call) → observe the result → repeat reasoning with updated context until the goal is met', C: 'Generate the final answer directly, then verify it with a single tool call', D: 'Execute all available tools in parallel, then reason over all outputs at once' },
    answer: 'B', explanation: 'ReAct interleaves Thought → Action → Observation in a loop, letting the agent revise its plan based on each tool result rather than committing to a fixed sequence upfront.' },

  { id: 20016, domain: 4, domainName: 'Deployment and Scaling', topic: 'Fleet Management', difficulty: 'medium', keywords: ['global rollout', 'agent management', 'high availability'], verified: false, recurrenceCount: 1,
    question: 'A large enterprise is rolling out AI customer support agents worldwide and needs to monitor, update, and manage all agent instances reliably. Which solution most effectively ensures reliable operation and simplified management at scale?',
    options: { A: 'Manually SSH into each regional deployment to apply updates', B: 'A centralized orchestration/management platform with automated deployment, health monitoring, versioned rollouts, and centralized logging across all regions', C: 'Independent, unmonitored deployments per region with no central visibility', D: 'A single shared instance serving all regions to avoid management overhead' },
    answer: 'B', explanation: 'Centralized orchestration with automated, versioned rollouts and unified health monitoring/logging is the standard approach for reliably managing large, geographically distributed agent fleets.' },

  { id: 20017, domain: 8, domainName: 'Reliability and Error Handling', topic: 'Validation for Production', difficulty: 'medium', keywords: ['validation', 'agent reliability', 'production'], verified: false, recurrenceCount: 2, type: 'multi', answerCount: 2,
    question: 'Which two validation approaches are MOST critical for ensuring agent reliability in production deployments? (Choose two.)',
    options: { A: 'Automated regression testing against a curated suite of representative and edge-case scenarios before each release', B: 'Continuous production monitoring with alerting on output quality, latency, and failure-rate metrics', C: 'One-time manual testing performed only before the very first launch', D: 'Relying solely on user complaints to surface issues' },
    answer: 'A,B', explanation: 'Pre-release regression testing catches known-scenario regressions before deployment, while continuous production monitoring catches drift and unknown failure modes after deployment — together they cover both pre- and post-release reliability.' },

  { id: 20018, domain: 9, domainName: 'Safety, Ethics, and Compliance', topic: 'Classifier-Based Guardrails', difficulty: 'medium', keywords: ['classifier branch', 'prompt filtering', 'guardrails'], verified: false, recurrenceCount: 1,
    question: 'You use a classifier branch as part of your semantic guardrail system to assess the risk of generated text. What is a key benefit of this compared to solely relying on prompt filtering?',
    options: { A: 'It eliminates the need for any latency budget in the pipeline', B: 'It evaluates the actual generated output\'s meaning/risk after generation, catching unsafe content that slipped past input-side prompt filters, and can be tuned/retrained independently of the prompt', C: 'It guarantees zero false positives', D: 'It removes the need for retrieval grounding' },
    answer: 'B', explanation: 'Prompt filtering only screens inputs; a classifier branch scores the actual generated output, catching cases where an innocuous input still produces risky content, and can be improved independently without touching prompt engineering.' },

  { id: 20019, domain: 10, domainName: 'Human-AI Interaction and Oversight', topic: 'Decision Transparency', difficulty: 'medium', keywords: ['explainability', 'transparency', 'multi-agent', 'no model changes'], verified: false, recurrenceCount: 1,
    question: 'Stakeholders want greater insight into how a multi-agent supply chain system decides on actions across tasks. Which approach would best improve decision transparency WITHOUT modifying the underlying model architecture?',
    options: { A: 'Retrain the models with an interpretability-focused loss function', B: 'Add structured decision logging/tracing (inputs, intermediate reasoning steps, tool calls, and final rationale) surfaced through an explainability dashboard', C: 'Replace all agents with simpler rule-based systems', D: 'Reduce the number of agents to one to simplify reasoning' },
    answer: 'B', explanation: 'Instrumenting the existing pipeline with structured tracing/logging exposes the reasoning and decision path to stakeholders through a dashboard, improving transparency purely at the observability layer — no model changes required.' },

  { id: 20020, domain: 6, domainName: 'Knowledge Integration and Data Handling', topic: 'RAG Architecture — Freshness & Latency', difficulty: 'medium', keywords: ['data freshness', 'latency', 'RAG architecture'], verified: false, recurrenceCount: 1,
    question: 'You are designing a RAG architecture and are concerned about data freshness and minimizing latency. Which is the most important consideration?',
    options: { A: 'Maximizing the number of documents indexed regardless of update frequency', B: 'An incremental/streaming indexing pipeline that keeps the vector store current with low-latency updates, paired with a retrieval path optimized for fast approximate nearest-neighbor search', C: 'Re-indexing the entire corpus from scratch on a fixed monthly schedule', D: 'Using the largest possible embedding model for maximum accuracy' },
    answer: 'B', explanation: 'Freshness requires incremental indexing so new/changed data is reflected quickly, while latency requires an efficient ANN retrieval path — a full monthly re-index or oversized embedding models would hurt one or both goals.' },

  { id: 20021, domain: 4, domainName: 'Deployment and Scaling', topic: 'Cross-Hardware Optimization', difficulty: 'hard', keywords: ['healthcare', 'sub-100ms', 'RTX', 'DGX', 'portability'], verified: false, recurrenceCount: 1,
    question: 'A healthcare AI company needs sub-100ms inference for diagnostic agents deployed across varied NVIDIA hardware (RTX 6000 workstations to DGX systems). Which optimization strategy gives the BEST performance while maintaining deployment flexibility?',
    options: { A: 'Hand-tune a separate custom model per hardware target with no shared pipeline', B: 'Use a hardware-portable inference optimization stack (e.g., TensorRT/TensorRT-LLM with quantization) that compiles/optimizes the same model per target GPU while preserving accuracy', C: 'Run the largest unquantized model everywhere and accept variable latency', D: 'Only support DGX systems and drop workstation deployments' },
    answer: 'B', explanation: 'A portable optimization stack like TensorRT with quantization lets the same base model be compiled/optimized for each specific GPU target, hitting latency SLAs across diverse hardware without maintaining fully separate models.' },
];